### ISSUE TITLE
Phprecipebook5Controller

### ISSUE THREAD

**Issue by vbroglio** [nazgul26/PHPRecipebook#1]
hello, my installation ask me for an "Phprecipebook5Controller.php" file. Since that file doesn't exists, how I can create it?
Thk & rgds

**Comment by nazgul26** [comment]
I have not packaged up PHPRecipebook 5.0 for installation. It is in development now and not quite ready for running out of the box without some work.  That being said, I don't know what could be giving you that error.  Do you have more details like some stack trace or additional logs?  With more details I might be able to help.

**Comment by vbroglio** [comment]
Hello, thanks for your answer.
You can find some information here: http://www.vinodb.it/phprecipebook5/
On monday I'll send you other infomations (I forgot my USB memory in
office),

Regards

Vittorio Broglio

2015-01-24 2:58 GMT+01:00 Todd Rogers notifications@github.com:

> I have not packaged up PHPRecipebook 5.0 for installation. It is in
> development now and not quite ready for running out of the box without some
> work. That being said, I don't know what could be giving you that error. Do
> you have more details like some stack trace or additional logs? With more
> details I might be able to help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nazgul26/PHPRecipebook/issues/1#issuecomment-71295202
> .

## 

Visita la mia galleria fotografica in http://www.ezvb.it
Visita Acquea.it (http://www.acquea.it), le sue foto ed il suo Almanacco
delle Immersioni.

**Comment by nazgul26** [comment]
Based on what I see, I think maybe the URL rewriting is not working so it does not load the right page.  Have you loaded the mod_rewrite module?

http://book.cakephp.org/2.0/en/installation/url-rewriting.html

**Comment by vbroglio** [comment]
My hosting provider is not "so liberal" about server configuration, so I
have used "core.php" modification. You can find this file here attached. If
you want, please check it out.

Thanks and regards

Vittorio

2015-01-25 2:34 GMT+01:00 Todd Rogers notifications@github.com:

> Based on what I see, I think maybe the URL rewriting is not working so it
> does not load the right page. Have you loaded the mod_rewrite module?
> 
> http://book.cakephp.org/2.0/en/installation/url-rewriting.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nazgul26/PHPRecipebook/issues/1#issuecomment-71346194
> .

## 

Visita la mia galleria fotografica in http://www.ezvb.it
Visita Acquea.it (http://www.acquea.it), le sue foto ed il suo Almanacco
delle Immersioni.

**Comment by nazgul26** [comment]
I didn't see an attachment.  But I setup my core.php to not use mod_rewrite and see some same stuff.  I can use the site using this is a start path:

phprecipebook/index.php/Recipes

But on yours I can't. I get a 'can't open file error'.  Little googling shows this idea to fix?
http://stackoverflow.com/questions/15869655/cannot-visit-cakephp-controllers-action-on-godaddy

I am going to keep working with mod_rewrite enabled but will put some work into docs for workarounds and will most likely have more ideas as I push to heroku and my hosting provider.

**Comment by nazgul26** [comment]
I have fixed a lot of bugs and successfully pushed to 2 hosts, Heroku and a basic CentOs Install.  Should resolve a lot of issues and setup.

**Comment by russbauer** [comment]
I'm wondering what all was done to fix this for Vittorio? Here's what I have happening.
1. GoDaddy is my web host
2. My site uses ssl, so my site's root directory already does the following
          Options +FollowSymLinks
          RewriteEngine On
          RewriteCond %{SERVER_PORT} !=443
          RewriteRule ^ https://www.mydomainnamehere.org/%{REQUEST_URI} [R,L]

```
      # BEGIN WordPress

      # END WordPress
```
1. Tried adding the following to my .htaccess in the root level
         RewriteBase /
2. Tried modifying Config/core.php while removing .htaccess files in webroot/ and app/
         Uncomment //Configure::write('App.baseUrl', env('SCRIPT_NAME'));
3. Ensured the temp directory is writable by the web user
4. I've cleared Clear the ./tmp/cache/models, ./tmp/cache/persistent directories

At the moment, I get the following when I hit the url in a browser:

Warning: include(/home/content/07/3042307/html/cookbook2/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 97

Warning: include(): Failed opening '/home/content/07/3042307/html/cookbook2/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php' for inclusion (include_path='.:/usr/local/php5_4/lib/php') in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 97

Fatal error: CakePHP core could not be found. Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php. It should point to the directory containing your /cake core directory and your /vendors root directory. in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 104

Any ideas what I might be missing?

I think the redesign looks wonderful. Well done!!! Thank you in advance for you assistance with this.
- Russ

**Comment by nazgul26** [comment]
Russ,

I think the problem is that the clone from GitHub would not include the 
CakePHP files. I switched over to composer to download those and didn't 
realize I should update the instructions.  Sorry about that.

I will setup a Download GitHub repo this weekend that will have the 
release packaged and ready to run. Thanks for trying to get it setup and 
sorry about the frustration.

Todd

**Comment by russbauer** [comment]
No problem, Todd. I just posted, creating a new issue on this. I think we submitted our responses literally at the same moment. I'll let you decide if you follow up here in this issue, or respond via the newly created issue. Sorry for the double-posting. I will watch for the new package this weekend.

Thank you,
- Russ
