### ISSUE TITLE
Notice (8): compact(): Undefined variable: recipe [APP/Controller/RecipesController.php, line 180]

### ISSUE THREAD

**Issue by afc54** [nazgul26/PHPRecipebook#100]
compact - [internal], line ??
RecipesController::edit() - APP/Controller/RecipesController.php, line 180
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 112

Is this one of the incompatibilities being resolved in the upgrade to 6.0?
Has no one else seen this?  Running with debug=2.  I get errors at just about every page.

**Comment by nazgul26** [comment]
Yes this should be resolved in all the upgrades I am doing.

**Comment by afc54** [comment]
Found this
https://stackoverflow.com/questions/28247317/cakephp-table-for-model-was-not-found-in-datasource-default
and one of the solutions proposed worked:
$ cd tmp/cache
$ find . -type f -delete
After doing this and resetting debug to 0 it seems to be working,  I
haven't entered any data yet, but at least no errors.

Thanks for replying.
