### ISSUE TITLE
PHPRecipeBook without ajax.googleapis.com

### ISSUE THREAD

**Issue by afc54** [nazgul26/PHPRecipebook#101]
I run NoScript for security and privacy.  No wonder PHPRecipeBook wasn't working right.  Not sure why but it attempts to go to ajax.googleapis.com.

After finding this:

https://stackoverflow.com/questions/17020284/is-it-possible-to-run-ajax-based-php-files-in-localhost-offline/17020444

it appears it is possible to run equivalent code locally.  The following:

libjs-jquery and libjs-jquery-[form,metadata,tablesorter,ui] were already installed.  Installed all other libjs-jquery-* packages I could find.

$ find . -type f -exec grep googleapis.com {} \; -print
                echo $this->Html->script("https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js");
                echo $this->Html->script("https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js");
./View/Layouts/setup.ctp
                echo $this->Html->css("https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css");
                echo $this->Html->script("https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js");
                echo $this->Html->script("https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js");
./View/Layouts/default.ctp
        echo $this->Html->css("http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css");
        echo $this->Html->script("https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js");
        echo $this->Html->script("http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js");
./View/Layouts/mobile.ctp

These are all the references to ajax.googleapis.com.  I'm not sure what they should be replaced with or if there's an automated way to make the code use the local libraries.

I've done:

php composer-setup.php
php composer.phar update

but it did nothing.

How can I use the local jquery packages instead of going to googleapis.com?

Thanks.

**Comment by FriedrichFroebel** [comment]
You could replace the corresponding with local resources, as it is done for `jquery.qtip.js` for example at the moment. Searching for the different projects (jQuery, jQuery UI, jQuery Mobile) with your favourite search engine should give you download options (much more recent versions by default).

**Comment by nazgul26** [comment]
Changed made in 6 Release.  Updated Jquery version while I was at it.
