### ISSUE TITLE
webhost config info?

### ISSUE THREAD

**Issue by smokinjo** [nazgul26/PHPRecipebook#102]
I moved servers recently, and I need t update PHPRecipeBook.

Which files contain the database and server information?

Once I find the file, what am I looking for ?

Thanks

Joseph

**Comment by nazgul26** [comment]
You will want to edit the <your phprecipebookdir>/Config/database.php file.

Look for this part:
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'root',
		'password' => '',
		'database' => 'phprecipebook',
		'prefix' => '',
		//'encoding' => 'utf8',
	);

and change it to be your new Db user/password.
