### ISSUE TITLE
Error on new server

### ISSUE THREAD

**Issue by smokinjo** [nazgul26/PHPRecipebook#103]
I recently moved PHPRecipe to a new server.

I updated the database information, and upon running it, I get some errors.

On m  old server, I used:
PHP 7.0   Mod PHP  (I tried PHP FPM but it would not work)

Onm my new server I am using:
PHP FPM
PHP 7.4

Here are the errors:

Warning: include(): open_basedir restriction in effect. File(/var/www/clients/client2/web5/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php) is not within the allowed path(s): (/var/www/clients/client1/web11/web:/var/www/clients/client1/web11/private:/var/www/clients/client1/web11/tmp:/var/www/joespace.ca/web:/srv/www/joespace.ca/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom) in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php on line 547

Warning: include(/var/www/clients/client2/web5/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php): failed to open stream: Operation not permitted in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php on line 547

Warning: include(): Failed opening '/var/www/clients/client2/web5/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php' for inclusion (include_path='.:/usr/share/php') in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php on line 547

Warning: set_error_handler() expects the argument (ErrorHandler::handleError) to be a valid callback in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/Configure.php on line 476

lines repeat themselves except the end:

Fatal error: Uncaught Error: Class 'ErrorHandler' not found in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php:957 Stack trace: #0 /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError() #1 [internal function]: App::shutdown() #2 {main} thrown in /var/www/clients/client1/web11/web/recipe/Vendor/cakephp/cakephp/lib/Cake/Core/App.php on line 957

I am not tech inclined, but a friend who does not work with Cake PHP will be i a better position to help. Maybe you might have a clue.

Thanks

**Comment by nazgul26** [comment]
Check to make sure Config/core.php has debug = 0;

Configure::write('debug', 0);

Or your hosting provider might have restrictions on place preventing loading files.

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

See if you can change those settings.

Also check the web user that is running as the site has permissions to the folder you extracted the files to.

**Comment by smokinjo** [comment]
Thanks for the reply.

My technician did something on the new server and it is working fine.

Problem i ssolved.

Thanks for your help.
