### ISSUE TITLE
Road map, fixes and features?

### ISSUE THREAD

**Issue by smokinjo** [nazgul26/PHPRecipebook#104]
Hello,

This is not an issue per say.

I would like to find a way to contribute to the project.  It is good software.

I am not a programmer, but want to contribute to the project somehow.  Maybe I can find a friend that can help, but 

Is there a way to see a road map and already requested feature adds and fixes needed.

I have some ideas, but want to see existing things brought for already.

Is the road map,  list of feature requests and fixes needed available on github?

Thanks

**Comment by nazgul26** [comment]
The big thing I am working on now is converting over to the latest version of CakePHP which will clean up a lot of setup issues on newer PHP.  Features that people have requested here on GitHub is probably the place to look and see what others are asking for and if you have a similar ask.  Feel free to add your wish list there.  

From my perspective I think an area I want to fix up is making it easier out of the box to be a single user system or a multi-user system.  Over the the years I have toggled between the two based on feedback and should settle it.
