### ISSUE TITLE
Demo set offline

### ISSUE THREAD

**Issue by KHome** [nazgul26/PHPRecipebook#107]
Hi,

I would like to check the new version 6.0 on the demo site.
Could you check to set this online back again?

BR,
KHome

**Comment by nazgul26** [comment]
Working on it.  Found a couple bugs after conversion I have to fix... like the 'Create Account' button not working.

**Comment by nazgul26** [comment]
Demo is updated. Create an account and then login.

**Comment by KHome** [comment]
Hi, it seems its not working again - please recheck
https://secure-hamlet-65587.herokuapp.com/

shows
 An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by nazgul26** [comment]
Heroku has removed free access.  Sadly I will have to remove the demo's since they want $ for everything now.

**Comment by KHome** [comment]
Oh, I did not knew that Heroku is "down" for free accounts.
Thank you for the hint. 

Do you know/provide any "easy" check and development environment of the latest version?
Proposal:

- a) Docker image
- b) VIrtual Machine (VDI)
- c) Raspberry image (to burn to SD Card)

BTW: I did some modifications for my installation based on version 5, see the "Matrix-View" attached.
![matrixview](https://user-images.githubusercontent.com/11480711/206899636-a5b3161a-56e3-458d-88cd-77be32fe5847.png)

**Comment by nazgul26** [comment]
I was thinking Docker.  Up next for me is to get things over the CakePHP v4.  I found this past week CakePHP 3 does not work on PHP 8 and that is starting to roll out more and more.
