### ISSUE TITLE
Upgrading 5.1.5 to 6.0 Beta on Rocky Linux 9

### ISSUE THREAD

**Issue by eliwap** [nazgul26/PHPRecipebook#108]
I recently upgraded my webserver from Rocky Linux 8 to 9.

Since phprecipebook 5.1.5 strained to support newer versions of php and could not run on php 8.x at all I had to upgrade phprecipebook to 6.0 beta if I wanted to use it. I upgraded successfully and everything seems to running just fine. Thanks for the new version :)

Anyhoot, these are the steps I took to upgrade phprecipebook.

I'm using /webroot to mean the folder where phprecipebook is installed. You may have phprecipebook installed in a different folder. Also you may have phprecipebook installed in a different folder as well. You will need to adjust path names as required.

As the root user

dnf install git

cd /webroot

mv /webroot/PHPRecipebook /webroot/PHPRecipebook.bak

You will need stuff from the older version.

git clone https://github.com/nazgul26/PHPRecipebook.git

cd PHPRecipebook

At this point the backup of the old installation comes in handy. You will need to copy files and info from /webroot/PHPRecipebook.bak/database.php.

cp /webroot/PHPRecipebook.bak/webroot/files /webroot/PHPRecipebook/webroot/files

At this stage, follow the directions at the sections "Server Install" and Directory Permissions section at https://github.com/nazgul26/PHPRecipebook. It would be wise to go to random password generator on the web to generate asecurity salt as indicated in the configuration file.

Now to install composer
------------------------

wget https://getcomposer.org/installer -O composer-installer.php

php composer-installer.php --filename=composer --install-dir=./

** the composer.lock is configured for php versions lower then what is available on Rocky Linux 9. The following command causes the installation to ignore the php version requirements.

./composer install --ignore-platform-req=php

answer yes to all the questions.

You will also be asked for a token. Please follow the instructions presented during the installation to acquire the token. After composer and cake are installed

chown -R apache:apache /webroot/PHPRecipebook

The user and group you use may be different so substitute if required.

You should be good to go.

**Comment by nazgul26** [comment]
Happy to hear the new release was well timed for you :-).  I have put out 6.2 version which has fixes for a couple of the rough edges.
