### ISSUE TITLE
SQL schema problems

### ISSUE THREAD

**Issue by Deadweasel** [nazgul26/PHPRecipebook#11]
I don't have the ability to import the database schema through a console script, so I attempted to import it with a desktop client instead, with only partial success due to some apparent errors in the structure code.  Specifically, these declarations are causing all kinds of fits trying to run them, and I don't know how to resolve them without potentially breaking app code down the road:

CREATE table attachments (
    id INT NOT NULL AUTO_INCREMENT,
    recipe_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    `name` varchar(32) NOT NULL,
    `attachment` varchar(255) NOT NULL,
    `dir` varchar(255) DEFAULT NULL,
    `type` varchar(255) DEFAULT NULL,
    `size` int(11) DEFAULT 0,
    sort_order INT
    PRIMARY KEY (`id`)  <==== WILL NOT IMPORT WHEN TICKS ARE USED AROUND 'id' HERE
);

CREATE TABLE ingredient_mappings (
    id INT NOT NULL AUTO_INCREMENT,
    recipe_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id INT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    quantity FLOAT NOT NULL,
    unit_id INT REFERENCES units(id) ON DELETE SET NULL,
    qualifier VARCHAR(32),
    optional BOOL,
    sort_order INT,
    PRIMARY KEY (ingredient_id,recipe_id)  <==== HOW CAN YOU HAVE TWO "PRIMARY" KEYS??  SERVER WILL NOT EVEN ALLOW ME TO MANUALLY ATTEMPT THIS.
);

CREATE TABLE related_recipes (
    id INT NOT NULL AUTO_INCREMENT,
    parent_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    recipe_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    required BOOL,
    sort_order INT,
    PRIMARY KEY (parent_id, recipe_id) <==== AGAIN, TWO PRIMARY KEYS??
);

The first table declaration imports just fine after removing the ticks around "id" at the PRIMARY KEY declaration.

The next two tables simply can't work (for me, at least) with the dual PRIMARY KEYs.  Are these truly errors in the SQL, or am I running into yet more issues with shared web hosting again?  I've never seen more than a single primary key in a table, but like I said, I'm no expert DBA so I can't say if that's legitimate or not.

**Comment by nazgul26** [comment]
What database system are you using?  Multiple primary keys are pretty common thing.
