### ISSUE TITLE
Bug in 6.1 : Mealplan can't open the recipe

### ISSUE THREAD

**Issue by eloewfr** [nazgul26/PHPRecipebook#110]
Hi,
In a filling Mealplan, when you click on a recipe, you become a window for changing Mealplan. You can't view the recipe anymore.

**Comment by nazgul26** [comment]
I see what went wrong.  Fix is in - 
https://github.com/nazgul26/PHPRecipebook/commit/6c19ba41c64c6c30f84fe55b6e316395c627c858

Will put out in next release or you can manually make the change now on your local copy.
