### ISSUE TITLE
Error in "Find by ingredient(s)"

### ISSUE THREAD

**Issue by eloewfr** [nazgul26/PHPRecipebook#111]
Hi,
when I search a recipe by ingredient, after make a selection of ingredient (juste one) and click on "search", i become an error :
"Cannot convert value of type `array` to string InvalidArgumentException"

**Comment by nazgul26** [comment]
Fixed checked in, that took a lot of CakePHP gymnastics to resolve.

Will put in next release.  You can get latest or grab RecipesController.php and contains.ctp if you want it sooner.
