### ISSUE TITLE
Core Ingredients not available

### ISSUE THREAD

**Issue by admorgan** [nazgul26/PHPRecipebook#13]
The core ingredients do not seem to be available. I am being forced to recreate all the work someone else already did. It doesn't matter if "Create with default ingredients" is selected or not.

**Comment by nazgul26** [comment]
merged the pull request.

**Comment by admorgan** [comment]
Unforunately the pull request didn't fix this issue, The pull fixed https://github.com/nazgul26/PHPRecipebook/issues/11

**Comment by nazgul26** [comment]
will retest...
and found that Core Ingredients used for the USDA name are failing with a 'Not Authorized Message'.  Also found creating a user has lots of warnings due the notEmpty Validator rule being deprecated.  Working on some fixes.  Without more details though can't be sure this is the exact issue you are having with it.

**Comment by nazgul26** [comment]
Fix permission issue on USDA name search in ingredients.  Hopefully that is the reported issue.
