### ISSUE TITLE
Issue when deleting item

### ISSUE THREAD

**Issue by daschenbrener** [nazgul26/PHPRecipebook#14]
I am able to create a recipe, but when I go to delete, this is the error on a white blank screen

Notice (8): Undefined index: image [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1987]
Code Context
UploadBehavior::_prepareFilesForDeletion() - APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1987
UploadBehavior::beforeDelete() - APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 432
ObjectCollection::trigger() - APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Model::delete() - APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php, line 2680
RecipesController::delete() - APP/Controller/RecipesController.php, line 232
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 113

your help is appreciated

**Comment by nazgul26** [comment]
Updating the the Upload module using Composer appears to resolve the issue.  Release will follow in about a week.

**Comment by daschenbrener** [comment]
Hi Todd, I have to apologize, I am unfamiliar with the composer. And am not familiar on using this method.

Also is there any way I can support you and this project? By some funds etc?

**Comment by nazgul26** [comment]
I have uploaded 5.0.5 that includes the updated plugin, that way you 
don't have to mess with Composer.

Don't require any donations or anything, just happy people find some 
value in what I am doing.

Todd

**Comment by daschenbrener** [comment]
Unfortunately. It didn’t fix the issue, and with this version I could not import any of the core or sample ingredients either.

Attached is the screenshot of the error

![error upload](https://cloud.githubusercontent.com/assets/15661340/11290990/d2ef16b8-8ef8-11e5-9156-9029897c5842.png)
