### ISSUE TITLE
Error message when adding image

### ISSUE THREAD

**Issue by daschenbrener** [nazgul26/PHPRecipebook#15]
when I go to create a new reciepe and add and image, this is the error that is returned. But the image appears to be added

![eoor adding image](https://cloud.githubusercontent.com/assets/15661340/10954659/0e24625e-830c-11e5-94dd-876edfd2cb36.png)

**Comment by nazgul26** [comment]
I have published release 5.0.5 that will include the updated Upload plugin.  Give a try and see if that resolved the issue.

**Comment by daschenbrener** [comment]
Will do, I will do this shortly.

**Comment by nazgul26** [comment]
Have a fix release 5.0.6.  Should take care of it.

**Comment by daschenbrener** [comment]
It appears so, I appreciate your attention and your work on this.
