### ISSUE TITLE
5.0.6 upgrade if admin account was renamed

### ISSUE THREAD

**Issue by russbauer** [nazgul26/PHPRecipebook#17]
Issue: Prior to this upgrade I had renamed my 'admin' user.

Symptoms: During the upgrade you receive the following error in a yellow window at the top of your browser.

![capture](https://cloud.githubusercontent.com/assets/11053928/11320007/c3440f70-9051-11e5-977a-d06605ad2cf0.PNG)

../Controller/SetupController.php (line 45)
array(
    'username' => array(
        (int) 0 => 'required',
        (int) 1 => 'required'
    ),
    'access_level' => array(
        (int) 0 => 'numeric',
        (int) 1 => 'numeric'
    )
)

Overview and resolution:
What I found during the upgrade to release 5.0.6 was that before I was able to successfully complete the upgrade wizard I needed to modify line 33 in ../Controllers/SetupController.php

From:   $user = $this->User->findByUsername('admin');

To:      $user = $this->User->findByUsername('myadminusernamehere');

Upon completion of the upgrade I modified this back to: $user = $this->User->findByUsername('admin');

**Comment by nazgul26** [comment]
fix committed.  Will still user 'admin' if that account is present. If not then user can type own admin account in text input.
