### ISSUE TITLE
Meal Master Import not working

### ISSUE THREAD

**Issue by daschenbrener** [nazgul26/PHPRecipebook#18]
I have tried to import a meal master file and i get the attached error
I have also attached the meal master import im trying to import

Thanks

![error meal master](https://cloud.githubusercontent.com/assets/15661340/11320767/099a59c4-9062-11e5-96d0-b7bbf9fb30e5.png)
[MM13000A.TXT](https://github.com/nazgul26/PHPRecipebook/files/40932/MM13000A.TXT)

**Comment by nazgul26** [comment]
I got past the above error by changing the link from recipes/index.ctp to:

```
            <li><?php echo $this->Html->link(__('Import'), array('controller' => 'import')); ?></li>
```

ajax links did not work for file uploads.  I think that worked in an earlier PHP version.  

Anyway, that got me the next error:
Notice (8): Undefined index: Or [APP/Controller/Component/MealMasterComponent.php, line 478]

and output showing that the recipes are bleeding together.  There must be some delimitator difference between your file and the random test file I used from the internet.

**Comment by nazgul26** [comment]
in MealMasterComponent.php

```
var $rxpEnd = '/^(M{20,200}|-{20,200}|-{5})/';
```

is a better ending string.  That got me past the next error.  

Notice (8): Undefined index: Or [APP/Controller/Component/MealMasterComponent.php, line 478]

Some other field is not reading quite right. I have mentioned that I hate MM format yet ;-).   It is a very loose format.

**Comment by daschenbrener** [comment]
i cant even imagine why they just didnt utilize some type of standards like delimited, or basic sql syntax,

**Comment by jpeters001** [comment]
Anyone gotten any further with this?  I have made the changes above but instead of getting ,
Notice (8): Undefined index: Or [APP/Controller/Component/MealMasterComponent.php, line 478]
I have been getting this error, 
Notice (8): Undefined index: lg [APP/Controller/Component/MealMasterComponent.php, line 478]
I was able to fix this by changing an ingredient line from 4 lg  Eggs; to 4 tb  Eggs; lg (large) is supposed to be an unprecise description of size for an ingredient. Anyway now I still get this error,
Undefined index: name [APP/Controller/Component/MealMasterComponent.php, line 283] 
not sure how to find this one??

**Comment by nazgul26** [comment]
Turns out I am not nearly as far along with the mealmaster import as I thought I was.  I got as far as parsing file but not creating recipes or ingredients. I am working on that now but it will take a couple of weeks at least.

**Comment by Daronna** [comment]
Hi;
I found that if I try to import a Meal Master recipe from the main page, I don't get the Controller error as noted above, I get the message below. It doesn't import the file, BUT it does save the ingredients even though some of these ingredients are duplicates in my database.

Any help would be appreciated
Daronna

Array
(
    [0] => Array
        (
            [Recipe] => Array
                (
                    [name] => 4 Egg Butter Cake
                    [ethnicity_id] => 10
                    [serving_size] => 1
                    [directions] =>   Sift together flour,baking powder and salt.  Cream shortening until smooth.
  Gradually add sugar, creaming until light and fluffy.  Add eggs one at a
  time, beating after each addition. Add dry ingred. alternately with water.
  Add vanilla.

```
            )

        [Ingredient] => Array
            (
                [0] => Array
                    (
                        [quantity] => 3
                        [unit_id] => 11
                        [name] => cake flour
                        [qualifier] => 
                    )

                [1] => Array
                    (
                        [quantity] => 2
                        [unit_id] => 11
                        [name] => sugar
                        [qualifier] => 
                    )

                [2] => Array
                    (
                        [quantity] => 4
                        [unit_id] => 13
                        [name] => baking powder
                        [qualifier] => 
                    )

                [3] => Array
                    (
                        [quantity] => 4
                        [unit_id] => 0
                        [name] => eggs
                        [qualifier] => 
                    )

                [4] => Array
                    (
                        [quantity] => 1/4
                        [unit_id] => 13
                        [name] => salt
                        [qualifier] => 
                    )

                [5] => Array
                    (
                        [quantity] => 1
                        [unit_id] => 11
                        [name] => water
                        [qualifier] => 
                    )

                [6] => Array
                    (
                        [quantity] => 1
                        [unit_id] => 11
                        [name] => shortening
                        [qualifier] => 
                    )

                [7] => Array
                    (
                        [quantity] => 1
                        [unit_id] => 13
                        [name] => vanilla
                        [qualifier] => 
                    )

            )

    )
```

)
Saved: cake flour
Saved: sugar
Saved: baking powder
Saved: eggs
Saved: salt
Saved: water
Saved: shortening
Saved: vanilla

**Comment by smokinjo** [comment]
I'd be interested in how to upload recipes.  I tried a few files of master meal format and even text file.

I can not get anything to work.

The text files contain many recipes in meal master format, and it just says that there are no meal master recipes in the file.

Would love to make this work, and/or get a good working directions showing how to import files.

Joseph
