### ISSUE TITLE
Can't get to load, not sure what the issue is.

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#19]
I think it may be a phprecipebook.conf issue, can you give me a sample of what mine should look like?

When I browse to the site, I get this:

setDataSource($g_rb_database_type,$g_rb_database_host,$g_rb_database_user,$g_rb_database_password,$g_rb_database_name); $SMObj->setDebug($g_rb_debug); $SMObj->openDataSource(); // open the connection $DB_LINK = $SMObj->getDataSource(); // get the database connection object (adodb) // Global function, isValidID() function isValidID($id) { if (empty($id)) return false; elseif ($id < 1) return false; elseif (version_compare(phpversion(), "5.2.0", ">=") && !filter_var($id, FILTER_VALIDATE_INT)) return false; elseif (!is_numeric($id)) return false; else return true; } // Global Function, isValidLetter() function isValidLetter($letter, $exception) { if (empty($letter)) return false; elseif (strlen($letter) > 1) return false; elseif ($letter == $exception) return true; elseif (!preg_match("/[A-Z\s_]/i", $letter) > 0) return false; else return true; } $LangUI = new LangUI; // handles translations global $g_browser_lang; // give global access to this information $g_browser_lang = getBrowserLanguage(); // preg_match for letters, numbers, underscore, and hyphen. Reject anything else $g_browser_lang = (preg_match('/^(\w|-)+$/', $g_browser_lang)) ? $g_browser_lang : null; // Load the language file based on config or logged in user if ($SMObj->getUserLoginID() != NULL) { $userID = $SMObj->getUserLoginID(); $details = $SMObj->getUserDetails($userID); include "lang/".$details['language'].".php"; } else if ($g_browser_lang != NULL) { //we found a browser match load it if it exists if (file_exists('lang/'.$g_browser_lang.'.php')) include "lang/".$g_browser_lang.".php"; else include "lang/".$g_rb_language.".php"; } else { //nothing matched, load the default include "lang/".$g_rb_language.".php"; } // Convience debugging option, shows what version the database thinks it is. if ($g_rb_debug) { require_once("classes/DBUtils.class.php"); $msg = DBUtils::checkDBSchemaVersion(); } // langArray is set in en.php, it.php...etc.. $LangUI->setLangArray( $langArray ); $LangUI->setEncoding($langEncoding); $SMObj->setTranslationObject($LangUI); // pass that info on to the security manager if ($SMObj->isSecureLogin()) { $SMObj->getLoginFormSubmit(); } else { // auto login if ($SMObj->getUserLoginID() == "") $SMObj->login(); } // End of Login/Session stuff, now on to displaying the page // // m = the module, cf modules directory, eg 'search' // preg_match for letters, numbers, underscore, and hyphen. Reject anything else $m = (isset($_GET['m']) && preg_match('/^(\w|-)+$/', $_GET['m'])) ? $_GET['m'] : $g_rb_default_module; // a = action, default is the index page of the module // preg_match for letters, numbers, underscore, and hyphen. Reject anything else $a = (isset($_GET['a']) && preg_match('/^(\w|-)+$/', $_GET['a'])) ? $_GET['a'] : ""; $mobile = preg_match('/_mob$/', $a); if ($a == "") { if ($IsMobileBrowser) { $a = $g_rb_default_mobile_page; $mobile = true; } else { $a = $g_rb_default_page; } } // print = format for printing (minimal formating) $print = isset( $_REQUEST['print'] ) ? $_REQUEST['print'] : 'no'; $format = isset( $_REQUEST['format'] ) ? $_REQUEST['format'] : 'yes'; // Load the header stuff if ($mobile) { require "themes/$g_rb_theme/header_mob.php"; } else { require "themes/$g_rb_theme/header.php"; } // preg_match for letters, numbers, underscore, and hyphen. Reject anything else if (!empty($_REQUEST['dosql']) && preg_match('/^(\w|-)+$/', $_REQUEST['dosql'])) { include "modules/$m/".$_REQUEST['dosql'].".php"; } $msg = $SMObj->getErrorMsg(); if ($msg != '') { echo $msg . "

"; $SMObj->setErrorMsg(''); //reset it, we have read it. } // Load the module that is requested if (file_exists("modules/$m/$a.php")) { include "modules/$m/$a.php"; } else { include "modules/$g_rb_default_module/$g_rb_default_page.php"; } if ($format == "yes") { if ($mobile) { // And the default mobile footer to close things require "themes/$g_rb_theme/footer_mob.php"; } else { // And the default footer to close things require "themes/$g_rb_theme/footer.php"; } } // Save the session infor and clean things up saveSecurityModel($SMObj); $LangUI->cleanUp(); ?> 

My phprecipebook.conf looks like this:
# (/etc/apache2/sites-available/phprecipebook.conf)
# 

<VirtualHost *:80>
        ServerAdmin me@me.com
        ServerName  recipe.me.com

```
    # Indexes + Directory Root.
    DirectoryIndex index.php index.html
    DocumentRoot /var/www/recipe.me.com/htdocs

    # Main directory
    <Directory /var/www/recipe.me.com/htdocs>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
    </Directory>

    # CGI Directory
    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Location /cgi-bin>
            Options +ExecCGI
    </Location>

    # Logfiles
    ErrorLog  ${APACHE_LOG_DIR}/recipe.me.com.error.log
    CustomLog ${APACHE_LOG_DIR}/recipe.me.com.access.log combined
```

</VirtualHost>

**Comment by nazgul26** [comment]
Your error above is from the 4.x release of PHPRecipebook.  You sure you are using the 5.0 code?

**Comment by withanhdammit** [comment]
Yes, I had a 4.x database, but was using the 5.x code attempting to upgrade the DB.
I ended up creating a new database and had both it and the 4.x db side by side (in phpmyadmin).  Manually edited the 4.x db fields to match the 5.x db, then exported the data and imported it into the new database.  It's up and running.  I've got a couple of other issues that I'll post.
