### ISSUE TITLE
Create account in demo

### ISSUE THREAD

**Issue by russbauer** [nazgul26/PHPRecipebook#2]
I tried creating an account in the demo but it appears /Users/login and /User/add are pointing to the /Users/login page, or at least the button seems to be trying to go to /User/add but is landing on /Users/login

Looking forward to diving deeper into the app.

**Comment by nazgul26** [comment]
Should be working now, sorry about that. It was set to require a authenticated user to create a new account even in public mode.  Update pushed to heroku.
