### ISSUE TITLE
URL rewriting might not properly configured on your server.

### ISSUE THREAD

**Issue by pyrorob** [nazgul26/PHPRecipebook#20]
Have followed all of the directions but don't seem to be able to get anything to work. Can't get past the setup page.
System info
Centos 5
php 5.3.3
MySQL 5.0.95

If I try to bypass the error page and create the new user account, I get an array error:
array(
    'username' => array(
        (int) 0 => 'required',
        (int) 1 => 'required'
    ),
    'access_level' => array(
        (int) 0 => 'numeric',
        (int) 1 => 'numeric'
    )
)
And then it has a link to the page throwing the error:
/PHPRecipebook/Controller/SetupController.php (line 38)

Can you help?

**Comment by nazgul26** [comment]
You can try to disable the URL rewrite option in the core config? have not extensively tested that route, but would probably have a better chance of working then directly jumping to pages.

**Comment by nazgul26** [comment]
no response going to close without anything to go on.

**Comment by pyrorob** [comment]
I backed down a couple of revs and was able to make things work.
