### ISSUE TITLE
Restaurants page when not logged in shows edit and delete links

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#21]
![screen shot 2015-12-29 at 8 48 07 pm](https://cloud.githubusercontent.com/assets/16404870/12046426/9f685f4a-ae6d-11e5-925a-0261ef2d5dc5.png)

**Comment by withanhdammit** [comment]
Also does not show Price Range, Dine-In/Carry-Out/Delivery/Credit flags, or the website link when they are set.
![screen shot 2015-12-29 at 8 45 09 pm](https://cloud.githubusercontent.com/assets/16404870/12046431/ab38a884-ae6d-11e5-9053-4130d504a30b.png)

**Comment by nazgul26** [comment]
Good find on the links. Thanks. Fix committed.  Will show the other fields on the index page on next change.

**Comment by nazgul26** [comment]
Showing the pricing and combined the address to another column. I remember why I did not put them on the page, not enough space using the current layout.  Putting out in this release. Will revisit this to re-space later. Probably make shown by name and then for more details

**Comment by withanhdammit** [comment]
Thanks!
