### ISSUE TITLE
Recipe edit

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#23]
After creating or editing a recipe, when you hit Submit it should take you back to the View Recipe screen not keep you on the Edit Recipe screen.

It took me a couple of tries before I realized it was actually saving my updates, I thought it kept going back to the Edit screen because there was something wrong with one of the fields.

**Comment by nazgul26** [comment]
Changed.   Will be in next release.  You can pull RecipesController.php if you want sooner.
