### ISSUE TITLE
Tried adding new recipe, getting error in index

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#26]
![screen shot 2015-12-29 at 9 57 02 pm](https://cloud.githubusercontent.com/assets/16404870/12046903/2eaa980e-ae77-11e5-80f6-d47224460391.png)

**Comment by withanhdammit** [comment]
```
<ul>
        <?php if (isset($recipe)) :?>
        <li><?php echo $this->Html->link(__('View Recipe'), array('action' => 'view', $recipe['Recipe']['id'])); ?></li>
```

$viewFile = '/var/www/recipe_site/phprecipebook-5.0.6/View/Recipes/edit.ctp'
$dataForView = array(
    'ethnicities' => array(
        (int) 1 => 'American',
        (int) 2 => 'Chinese',
        (int) 3 => 'German',
        (int) 4 => 'Greek',
        (int) 5 => 'Italian',
        (int) 6 => 'Japanese',
        (int) 7 => 'Mexican',
        (int) 8 => 'Middle Eastern',
        (int) 9 => 'None',
        (int) 10 => 'Slavic',
        (int) 11 => 'Polish'
    ),
    'baseTypes' => array(
        (int) 1 => 'Beef',
        (int) 2 => 'Bread',
        (int) 3 => 'Egg',
        (int) 4 => 'Fruit',
        (int) 5 => 'Grain',
        (int) 6 => 'Lamb',
        (int) 7 => 'Other',
        (int) 8 => 'Pasta',
        (int) 9 => 'Pork/Ham',
        (int) 10 => 'Poultry',
        (int) 11 => 'Seafood',
        (int) 12 => 'Vegetable'
    ),
    'courses' => array(
        (int) 1 => 'Breakfast',
        (int) 2 => 'Snack',
        (int) 3 => 'Lunch',
        (int) 4 => 'Appetizer',
        (int) 5 => 'Side Dish',
        (int) 6 => 'Entree',
        (int) 7 => 'Dessert',
        (int) 8 => 'Beverage'
    ),
    'preparationTimes' => array(
        (int) 1 => '0 Minutes',
        (int) 2 => '1-10 Minutes',
        (int) 3 => '10-30 Minutes',
        (int) 4 => '30-60 Minutes',
        (int) 5 => '60+ Minutes'
    ),
    'difficulties' => array(
        (int) 1 => 'Easy',
        (int) 2 => 'Intermediate',
        (int) 3 => 'Difficult',
        (int) 4 => 'Expert'
    ),
    'sources' => array(
        (int) 3 => 'Family recipe',
        (int) 4 => 'Unknown',
        (int) 7 => 'Internet',
        (int) 8 => 'Newspaper'
    ),
    'preparationMethods' => array(
        (int) 1 => 'Slow cooker',
        (int) 2 => 'Microwave',
        (int) 3 => 'BBQ',
        (int) 4 => 'Canning',
        (int) 5 => 'Stove top',
        (int) 6 => 'Oven',
        (int) 7 => 'Ice cream maker',
        (int) 9 => 'Freezer',
        (int) 10 => 'None',
        (int) 11 => 'Blender'
    ),
    'recipe' => array(),
    'units' => array(
        (int) 1 => 'Each',
        (int) 2 => 'Slice',
        (int) 3 => 'Clove',
        (int) 4 => 'Pinch',
        (int) 5 => 'Package',
        (int) 6 => 'Can',
        (int) 7 => 'Drop',
        (int) 8 => 'Bunch',
        (int) 9 => 'Dash',
        (int) 10 => 'Carton',
        (int) 11 => 'Cup',
        (int) 12 => 'Tablespoon',
        (int) 13 => 'Teaspoon',
        (int) 14 => 'Pound',
        (int) 15 => 'Ounce',
        (int) 16 => 'Pint',
        (int) 17 => 'Quart',
        (int) 18 => 'Gallon',
        (int) 19 => 'Milligram',
        (int) 20 => 'Centigram',
        (int) 21 => 'Gram',
        (int) 22 => 'Kilogram',
        (int) 23 => 'Milliliter',
        (int) 24 => 'Centiliter',
        (int) 25 => 'Liter',
        (int) 26 => 'Deciliter',
        (int) 27 => 'Tablespoon_m',
        (int) 28 => 'Teaspoon_m',
        (int) 29 => 'Dozen'
    ),
    'allowAccountCreation' => false,
    'isEditor' => true,
    'isAdmin' => true,
    'loggedInuserId' => '2',
    'loggedIn' => true
)
$ethnicities = array(
    (int) 1 => 'American',
    (int) 2 => 'Chinese',
    (int) 3 => 'German',
    (int) 4 => 'Greek',
    (int) 5 => 'Italian',
    (int) 6 => 'Japanese',
    (int) 7 => 'Mexican',
    (int) 8 => 'Middle Eastern',
    (int) 9 => 'None',
    (int) 10 => 'Slavic',
    (int) 11 => 'Polish'
)
$baseTypes = array(
    (int) 1 => 'Beef',
    (int) 2 => 'Bread',
    (int) 3 => 'Egg',
    (int) 4 => 'Fruit',
    (int) 5 => 'Grain',
    (int) 6 => 'Lamb',
    (int) 7 => 'Other',
    (int) 8 => 'Pasta',
    (int) 9 => 'Pork/Ham',
    (int) 10 => 'Poultry',
    (int) 11 => 'Seafood',
    (int) 12 => 'Vegetable'
)
$courses = array(
    (int) 1 => 'Breakfast',
    (int) 2 => 'Snack',
    (int) 3 => 'Lunch',
    (int) 4 => 'Appetizer',
    (int) 5 => 'Side Dish',
    (int) 6 => 'Entree',
    (int) 7 => 'Dessert',
    (int) 8 => 'Beverage'
)
$preparationTimes = array(
    (int) 1 => '0 Minutes',
    (int) 2 => '1-10 Minutes',
    (int) 3 => '10-30 Minutes',
    (int) 4 => '30-60 Minutes',
    (int) 5 => '60+ Minutes'
)
$difficulties = array(
    (int) 1 => 'Easy',
    (int) 2 => 'Intermediate',
    (int) 3 => 'Difficult',
    (int) 4 => 'Expert'
)
$sources = array(
    (int) 3 => 'Family recipe',
    (int) 4 => 'Unknown',
    (int) 7 => 'Internet',
    (int) 8 => 'Newspaper'
)
$preparationMethods = array(
    (int) 1 => 'Slow cooker',
    (int) 2 => 'Microwave',
    (int) 3 => 'BBQ',
    (int) 4 => 'Canning',
    (int) 5 => 'Stove top',
    (int) 6 => 'Oven',
    (int) 7 => 'Ice cream maker',
    (int) 9 => 'Freezer',
    (int) 10 => 'None',
    (int) 11 => 'Blender'
)
$recipe = array()
$units = array(
    (int) 1 => 'Each',
    (int) 2 => 'Slice',
    (int) 3 => 'Clove',
    (int) 4 => 'Pinch',
    (int) 5 => 'Package',
    (int) 6 => 'Can',
    (int) 7 => 'Drop',
    (int) 8 => 'Bunch',
    (int) 9 => 'Dash',
    (int) 10 => 'Carton',
    (int) 11 => 'Cup',
    (int) 12 => 'Tablespoon',
    (int) 13 => 'Teaspoon',
    (int) 14 => 'Pound',
    (int) 15 => 'Ounce',
    (int) 16 => 'Pint',
    (int) 17 => 'Quart',
    (int) 18 => 'Gallon',
    (int) 19 => 'Milligram',
    (int) 20 => 'Centigram',
    (int) 21 => 'Gram',
    (int) 22 => 'Kilogram',
    (int) 23 => 'Milliliter',
    (int) 24 => 'Centiliter',
    (int) 25 => 'Liter',
    (int) 26 => 'Deciliter',
    (int) 27 => 'Tablespoon_m',
    (int) 28 => 'Teaspoon_m',
    (int) 29 => 'Dozen'
)
$allowAccountCreation = false
$isEditor = true
$isAdmin = true
$loggedInuserId = '2'
$loggedIn = true
$recipeId = ''

include - APP/View/Recipes/edit.ctp, line 262
View::_evaluate() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 113

**Comment by withanhdammit** [comment]
include - APP/View/Recipes/edit.ctp, line 262
View::_evaluate() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 113

**Comment by nazgul26** [comment]
Any additional details, like if it ever works... and what is done differently then?

**Comment by nazgul26** [comment]
No response, closing.
