### ISSUE TITLE
Install wizard didn't run

### ISSUE THREAD

**Issue by admorgan** [nazgul26/PHPRecipebook#29]
I re-installed due to the issue with updating the schema I posted earlier. Everything seems to be working fine now, but when I did the installation there was not a wizard to create the database entries or any wizard at all. I had to manually run cake schema create.

**Comment by nazgul26** [comment]
The database wizard will not create the DB.  The wizard currently only gives guidance and then is used to set the initial password.  So while a wizard, not completely do it all wizard.  Maybe later we will get there.

**Comment by admorgan** [comment]
That didn't happen either.
