### ISSUE TITLE
CakePHP core could not be found  and  failed to open stream

### ISSUE THREAD

**Issue by russbauer** [nazgul26/PHPRecipebook#3]
I see there's a closed issue related to this, but I'm wondering what all was done to fix this for Vittorio? Here's what I have happening.
1. GoDaddy is my web host
2. My site uses ssl, so my site's root directory already does the following
Options +FollowSymLinks
RewriteEngine On
RewriteCond %{SERVER_PORT} !=443
RewriteRule ^ https://www.mydomainnamehere.org/%{REQUEST_URI} [R,L]

```
  # BEGIN WordPress

  # END WordPress

Tried adding the following to my .htaccess in the root level RewriteBase /
Tried modifying Config/core.php while removing .htaccess files in webroot/ and app/ Uncomment //Configure::write('App.baseUrl', env('SCRIPT_NAME'));
Ensured the temp directory is writable by the web user
I've cleared Clear the ./tmp/cache/models, ./tmp/cache/persistent directories
```

At the moment, I get the following when I hit the url in a browser:

Warning: include(/home/content/07/3042307/html/cookbook2/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 97

Warning: include(): Failed opening '/home/content/07/3042307/html/cookbook2/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php' for inclusion (include_path='.:/usr/local/php5_4/lib/php') in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 97

Fatal error: CakePHP core could not be found. Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php. It should point to the directory containing your /cake core directory and your /vendors root directory. in /home/content/07/3042307/html/cookbook2/webroot/index.php on line 104

Any ideas what I might be missing?

I think the redesign looks wonderful. Well done!!! Thank you in advance for you assistance with this.

```
Russ
```

**Comment by nazgul26** [comment]
Please give the packaged release a try from https://github.com/nazgul26/PHPRecipebook-Download,  I am pretty sure that is the issue.
