### ISSUE TITLE
Adding to shopping list does not work

### ISSUE THREAD

**Issue by doppelgrau** [nazgul26/PHPRecipebook#30]
When I add a recipe to the shopping list, I get an error that I'm not the owner of the list.
(testet on demo site):
![bildschirmfoto 2016-01-06 um 19 46 53](https://cloud.githubusercontent.com/assets/6315907/12151243/79fb6c9c-b4ae-11e5-9485-4eeb30f27c89.png)

**Comment by tigershadowclaw** [comment]
I am getting this issue as well on my own server.  Did you ever determine a solution?

Server details:
Apache2 
PHP 7.0.32-0ubuntu0.16.04.1
MySQL 5.7.24-0ubuntu0.16.04.1

**Comment by tigershadowclaw** [comment]
Nevermind I figured it out.  You have login with an Administrator account and verify that the account being used has the role of either Editor or Administrator
