### ISSUE TITLE
Added new recipe, shows error when viewing

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#33]
<img width="1190" alt="screen shot 2016-01-14 at 6 53 09 am" src="https://cloud.githubusercontent.com/assets/16404870/12327462/8e0a9590-ba8b-11e5-8502-7ca047281110.png">

Error text says:
Notice (8): Undefined index: name [APP/View/Recipes/view.ctp, line 161]
Code Context
                            $quantity = $this->Fraction->toFraction($quantity);
                            $unit = $recipe['IngredientMapping'][$i]['Unit']['name'];
                            $ingredientName = $recipe['IngredientMapping'][$i]['Ingredient']['name'];
$viewFile = '/var/www/recipe.mysite.net/phprecipebook-5.0.7/View/Recipes/view.ctp'
$dataForView = array(
    'servings' => null,
    'recipe' => array(
        'Recipe' => array(
            'id' => '33',
            'name' => 'A-Test',
            'ethnicity_id' => '1',
            'base_type_id' => '1',
            'course_id' => '1',
            'preparation_time_id' => '2',
            'difficulty_id' => '1',
            'serving_size' => '1',
            'directions' => 'Cook the damn thing.',
            'comments' => 'Test',
            'source_description' => 'Ugh',
            'recipe_cost' => null,
            'modified' => '2016-01-14',
            'picture' => null,
            'picture_type' => null,
            'private' => false,
            'system' => 'usa',
            'source_id' => '4',
            'user_id' => '2',
            'preparation_method_id' => '5'
        ),
        'Ethnicity' => array(
            'name' => 'American'
        ),
        'BaseType' => array(
            'name' => 'Beef'
        ),
        'Course' => array(
            'name' => 'Breakfast'
        ),
        'PreparationTime' => array(
            'name' => '1-10 Minutes'
        ),
        'Difficulty' => array(
            'name' => 'Easy'
        ),
        'Source' => array(
            'name' => 'Unknown',
            'id' => '4',
            'description' => ''
        ),
        'User' => array(
            'name' => 'withanh',
            'id' => '2'
        ),
        'RelatedRecipe' => array(),
        'IngredientMapping' => array(
            (int) 0 => array(
                [maximum depth reached]
            )
        ),
        'Image' => array(),
        'Review' => array()
    ),
    'allowAccountCreation' => false,
    'isEditor' => true,
    'isAdmin' => true,
    'loggedInuserId' => '2',
    'loggedIn' => true
)
$servings = '1'
$recipe = array(
    'Recipe' => array(
        'id' => '33',
        'name' => 'A-Test',
        'ethnicity_id' => '1',
        'base_type_id' => '1',
        'course_id' => '1',
        'preparation_time_id' => '2',
        'difficulty_id' => '1',
        'serving_size' => '1',
        'directions' => 'Cook the damn thing.',
        'comments' => 'Test',
        'source_description' => 'Ugh',
        'recipe_cost' => null,
        'modified' => '2016-01-14',
        'picture' => null,
        'picture_type' => null,
        'private' => false,
        'system' => 'usa',
        'source_id' => '4',
        'user_id' => '2',
        'preparation_method_id' => '5'
    ),
    'Ethnicity' => array(
        'name' => 'American'
    ),
    'BaseType' => array(
        'name' => 'Beef'
    ),
    'Course' => array(
        'name' => 'Breakfast'
    ),
    'PreparationTime' => array(
        'name' => '1-10 Minutes'
    ),
    'Difficulty' => array(
        'name' => 'Easy'
    ),
    'Source' => array(
        'name' => 'Unknown',
        'id' => '4',
        'description' => ''
    ),
    'User' => array(
        'name' => 'withanh',
        'id' => '2'
    ),
    'RelatedRecipe' => array(),
    'IngredientMapping' => array(
        (int) 0 => array(
            'recipe_id' => '33',
            'ingredient_id' => '0',
            'quantity' => '1',
            'unit_id' => '1',
            'qualifier' => '',
            'optional' => false,
            'sort_order' => '0',
            'id' => '287',
            'Ingredient' => array([maximum depth reached]),
            'Unit' => array(
                [maximum depth reached]
            )
        )
    ),
    'Image' => array(),
    'Review' => array()
)
$allowAccountCreation = false
$isEditor = true
$isAdmin = true
$loggedInuserId = '2'
$loggedIn = true
$recipeId = '33'
$scale = (int) 1
$numberOfReviews = (int) 0
$averageRating = (int) 0
$imageCount = (int) 0
$i = (int) 0
$quantity = (int) 1
$unit = 'Each'
include - APP/View/Recipes/view.ctp, line 161
View::_evaluate() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 113

**Comment by withanhdammit** [comment]
Had to manually update the schema (add missing columns from tables).

ALTER TABLE recipes ADD image VARCHAR(255);
ALTER TABLE recipes ADD image_dir VARCHAR(255);
ALTER TABLE vendors ADD request_type VARCHAR(10) NULL DEFAULT 'GET';
ALTER TABLE vendors ADD format VARCHAR(255) NULL;
ALTER TABLE vendor_products ADD name VARCHAR(255);

**Comment by withanhdammit** [comment]
Sorry, this issue is still valid.  A new user does not show any ingredients and displays the error.

It does not appear to e related to the schema being off as I had originally suspected.  It appears to be related the the new user not having access to any of the ingredients.

**Comment by nazgul26** [comment]
No ingredients are created by default unless the admin user has ingredients and new user has selected to add an ingredient.  Can yo confirm that adding at least 1 ingredient takes care of this?  I could add validation on save to ensure 1 ingredient on new recipes.

**Comment by aquada** [comment]
I have installed today and also got this problem. I had typed in the ingredients for the recipe manually and not added them previously. Only found the answer by looking here - adding all the ingredients resolved the problem. Thanks for the software :)
