### ISSUE TITLE
URL scheme not being honored (HTTPS to HTTP downgrade)

### ISSUE THREAD

**Issue by cybe** [nazgul26/PHPRecipebook#35]
I'm using the current release version 5.0.8 of PHPRecipebook and noticed an HTTPS to HTTP downgrade. I assume the automatic detection of the full base URL ignores the protocol scheme.

**Steps to reproduce:**
1. Activate SSL on nginx
2. Access the application via https://recipes.example.org
3. Click on login

**Expected result:**
The browsing location is https://recipes.example.org/users/login

**Actual result:**
The browsing location is http://recipes.example.org/users/login

**Workaround:**
Force access to the webapplication to use HTTPS either via
1. Configure::write('App.fullBaseUrl', 'https://recipes.example.org'); or an
2. appropiate URL rewrite in nginx configuration

**Comment by nazgul26** [comment]
Thanks.

I tried to reproduce and couldn't.  Using Apache and clicking on the 
'Sign In' link stays https.  The link is a relative one, so baffling as 
to why it would put you back to http.  Could you inspect the link for me 
and confirm what route the link is set to?

**Comment by cybe** [comment]
Thanks for your reply,

I investigated the situation a bit further. The 'Sign In' link is indeed a relative one. But when I click it, it results in a redirect (HTTP 302):

```
GET /Users/login HTTP/1.1
Host: recipes.example.net
Referer: https://recipes.example.net/

HTTP/1.1 302 Found
Location: http://recipes.example.net/users/login
```

I can trigger the same redirect, when I browse the login site directly via `https://recipes.example.net/Users/login`. What catched my eye though was the capitalized path `/Users/login` in the original request compared to the lower case `u` in `users` in the redirect location. Browsing the login site directly via the uncapitalized  variant `https://recipes.example.net/users/login` does not result in a redirect and I stay on HTTPS.

When forcing the site URL to be HTTPS via `App.fullBaseUrl`, the same redirect from `/Users/login` to `/users/login` happens. But the URL scheme of the redirect location remains HTTPS.

**Comment by cybe** [comment]
By the way, I can trigger the exact same behavior on the heroku demo app: https://phprecipebook.herokuapp.com

**Comment by nazgul26** [comment]
Could you try 5.0.9 release?  I could not test out on Heroku since I ran 
into issues with their latest PHP.

I could recreate the issue by typing in User/login vs user/login before 
I pushed the bad version.

So I think you are right on the root cause.

Thanks,

Todd

**Comment by cybe** [comment]
The original downgrade on between ´/Users/login´ and ´/users/login´ has been fixed. There's also no unnecessary redirect.

But I triggered the downgrade again during login. After clicking the actual 'Sign In' button on the `/users/login` page, I received a HTTP redirect to the main page `/`:

```
POST /users/login HTTP/1.1
Referer: https://recipes.example.net/users/login

HTTP/1.1 302 Found
Location: http://recipes.example.net/
```

This also happens during logout:

```
GET /users/logout HTTP/1.1
Referer: https://recipes.example.net/

HTTP/1.1 302 Found
Location: http://recipes.example.net/
```

During user creation (Which btw. redirects wrongly to the recipe edit page):

```
POST /users/add HTTP/1.1
Referer: https://recipes.example.net/users/add

HTTP/1.1 302 Found
Location: http://recipes.example.net/recipes/edit
```

And user deletion:

```
POST /users/delete/2 HTTP/1.1
Referer: https://recipes.example.net/users

HTTP/1.1 302 Found
Location: http://recipes.example.net/users
```

And maybe on some other occurences I didn't check.

**Comment by nazgul26** [comment]
Glad to hear just changing the route to lower case took care of it. I 
will track down the others later this week.

**Comment by nazgul26** [comment]
Found one causing the logout redirect (RecipeLinkBox), changed to start with lower and now works on Heroku.  Get release 5.0.10. Thanks.
