### ISSUE TITLE
Error 500 on Install

### ISSUE THREAD

**Issue by kailledargun** [nazgul26/PHPRecipebook#36]
I built a fresh CentOS 7 install. I installed epel-release, httpd, mariadb, php, php-mysql, php-mcrypt, php-gd. I put the firewall rules in and it will serve an info.php. I then untar the files into /var/www/html/phprecipebook. I chown -R apache:apache /var/www/html/phprecipebook to make sure permissions were good. I created a database and changed the db config. When I browse http://ipaddress/phprecipebook or http://ipaddress/phprecipebook/index.php I get http error 500. I followed the instructions for mod_rewrite on apache2.4 but it didn't help. P

**Comment by cybe** [comment]
Please attach the log output from Apache and the PHP executor.

**Comment by kailledargun** [comment]
Thanks. That pointed me to the fact that selinux was still enabled. After disabling it I am up and running.
