### ISSUE TITLE
Cannot input Chinese characters

### ISSUE THREAD

**Issue by fromthestone** [nazgul26/PHPRecipebook#39]
i'm trying to add a recipe in chinese but save the name with "????" only...
i discovered that all tables are created with charset latin1_swedish_ci instead utf8
Please note that in database conf i have chosen utf8 and my db is set on utf8...

**Comment by nazgul26** [comment]
I see where that might be set in schema.php and then database.php for connection info.  I will try a clean install and see if changing those fixes it.  Hopefully I can convert existing installs as well without much issue.
