### ISSUE TITLE
Import from webpage?

### ISSUE THREAD

**Issue by Noiden** [nazgul26/PHPRecipebook#40]
Hello,

This is not really an issue, more a wanted feature.

I used "Gourmet Recipe Manager" but wanted a better webinterface for my recipies so I installed this.
But i'm missing one of the best functions from "Gourmet..." and that is to import recipies from web pages.

That would be cool if you cold do this in this app to.

Best Regards,
Noiden

**Comment by smokinjo** [comment]
This would be a great feature!!!

**Comment by nazgul26** [comment]
I can't think of a feasible way to do this.
