### ISSUE TITLE
Clean install giving errors

### ISSUE THREAD

**Issue by nikesfs** [nazgul26/PHPRecipebook#42]
Hi,

I tried to install the project clean, and got errors straight afterwards.
This is on a shared hosting plan so am unable to run linux commands.

_Table meal_plans for model MealPlan was not found in datasource default.
Table attachments for model Image was not found in datasource default.
Table shopping_lists for model ShoppingList was not found in datasource default.
Table restaurants for model Restaurant was not found in datasource default._

I  assure you those tables exist in the db.

Thanks

![tables](https://cloud.githubusercontent.com/assets/6930937/17214615/bf51442e-54d1-11e6-9241-1f55e967fe50.png)

**Comment by nazgul26** [comment]
Try clearing the Temp Folders.  Even without a command line you can do this.  Using any FTP connection/UI you may have to remove files from:

[your install dir]/tmp/cache/ 

go into each dir and remove files.

That will let CakePHP look at the DB again to see your tables.

**Comment by nikesfs** [comment]
Many thanks Todd,

That sounds right. It seemed like it would  be something like this , I just
didn't know where to look.

I can do that fine, I just mentioned the shared hosting because if it was a
case of chmod and things like this, I would definitely not be able to run.

I appreciate your help very much.

I will let you know how it went.

Kindest regards,
Nik
