### ISSUE TITLE
Styling suggestion

### ISSUE THREAD

**Issue by nikesfs** [nazgul26/PHPRecipebook#43]
Hi guys,

thanks for the help for the clean install bit. I have a layout suggestion and that is to remove the font-size rule for the qtip. 

Thanks

![qtip1](https://cloud.githubusercontent.com/assets/6930937/17321000/3cceeaa4-588e-11e6-9d91-2e0c363329e8.png)
![qtip2](https://cloud.githubusercontent.com/assets/6930937/17321002/41474284-588e-11e6-8496-6bc35e6b461a.png)

**Comment by nazgul26** [comment]
Works for me. I have no idea why I originally bumped up the font on that.  Change checked in.
