### ISSUE TITLE
Undefined function d()

### ISSUE THREAD

**Issue by amura11** [nazgul26/PHPRecipebook#45]
[Line 106](https://github.com/nazgul26/PHPRecipebook/blob/master/View/Setup/index.ctp#L106) in /View/Setup/index.cpt has an undefined function. The line reads:
`echo d('setup','error Message:' ) . $errorMsg;`
where it should be
`echo __d('setup','error Message:' ) . $errorMsg;`

**Comment by nazgul26** [comment]
Fix check in.  Will be in next release.
