### ISSUE TITLE
Allow only authenticated users?

### ISSUE THREAD

**Issue by kailledargun** [nazgul26/PHPRecipebook#46]
Is there a way to only allow authenticated users. I would like to make sure only approved people can see any part of the recipes. I use it as a family heirloom cookbook so we want to be able to share the recipes in the family but not outside.

**Comment by nazgul26** [comment]
Yes!  Shouldn't be to hard to force a login on all pages based on a config setting.  In about a month when the weather turns I will work on this.

**Comment by kailledargun** [comment]
Thanks! I appreciate it and love this app!!!

**Comment by nazgul26** [comment]
This is done.  There is a new config setting:

Configure::write('App.privateCollection', TRUE);

Set it as TRUE and it will require login for any viewing.  It will show the side bar of # of recipes but that is all.  

It will be out in next release (before end of year).
