### ISSUE TITLE
Online Vendor Product Codes

### ISSUE THREAD

**Issue by doom1979** [nazgul26/PHPRecipebook#5]
Hi
I'm quite new to php and trying to learn the ropes! I've managed to get phprecipebook working and now trying out the new online shopping feature in version 5.0 which is great but it seems the product code is not pulled back from the vendor product table into the shopping list?

I added an ingredient, and selected the online vendor. If i click add nothing happens, however if i repaste the product code into the entry box next to add, then click add, then it works!

Any thoughts?
Dom

**Comment by nazgul26** [comment]
The situation where you say it works sounds like the way I am currently using it.  This is what I do:
- Create meal plan.
- Add to shopping list
- Go Shopping button
- Remove items I have
- Shop online button
- Find product codes on 'Vendor' website and put them in the text boxes.  I have to use browser dev tools to find the IDs (pain).
- Test them by then clicking the 'add' link. 

It has been about 2 weeks of doing this and at this point I have 3-4 items I have to add per run.  So now I first press the 'Add All' button which puts all the items I know the product codes for in my cart. Without an API or master list from the vendor that is the best I could come up with.  

Now is the part where I need some suggestions for improvements.  What would make this easier but still be simple?  I have couple ideas for improvements including:
- Share product IDs across users, allow them to take the default or add their own as a override.
- Allow ingredients to have more than 1 product ID, add some more data for each like price/size/name.  This way if you want turkey deli meat one week and chicken the next you could select at checkout.
- Some script to crawl the vendor website and build a list from that.  That would have to most likely be a one-of process run during setup or something.

What you think?  Any of those worthwhile or is there something I am missing?

Thanks,

Todd

**Comment by nazgul26** [comment]
no response closing.  Will move along and change.
