### ISSUE TITLE
Import RecipeML or PHPRecipeBook Format

### ISSUE THREAD

**Issue by ducky007** [nazgul26/PHPRecipebook#52]
Would really like to be able to import my old recipes from PhpRecipeBook 2.3x, but it only exports in either RecipeML or PhpRecipeBook XML formats. Any chance of being able to import these?

**Comment by jodosh** [comment]
bump on this. I have a long running install on phprecipe 4.09 that I would love to move to the 5.X branch but without import it is a pain.

**Comment by Efus10n** [comment]
Came here to post this same request. I've been on 4.09 and found 5.x but don't know how to transfer all my recipes to it. The 5.x DB schema seems quite a bit different and there doesn't seem to be a script available to upgrade an existing 4.x DB to the 5.x schema.
