### ISSUE TITLE
Using Backup Database

### ISSUE THREAD

**Issue by upsidedowncake** [nazgul26/PHPRecipebook#57]
I have a server using Amahi and recently it had a pretty catastrophic error so I've had to largely start from scratch.  I reinstalled Recipebook, and I have a backup of the old app so I was hoping to use my old recipe database so that i'm not starting from the beginning.  My old system that crashed was Amahi 9 and I reinstalled a fresh install of Amahi 10, but I didn't think that impacted the PHPRecipeBook version #.  I was hoping to be able to move the 'recipedb.sql' file from the backup in to the newly installed location but I'm rather lost on next steps or getting everything to work right.  Any help is greatly appreciated, I'm a novice in PHP, Linux, coding, etc.

**Comment by nazgul26** [comment]
If you are using PHPRecipeBook 5.0 (and not 4.0 or older) than restoring should be pretty straightforward.  

* Ensure you have the following PHP Modules installed: mcrypt, gd. And mysql, pgsql or your DB. 
* Create a new database to store the application in. i.e. recipebook 
* Restore/Run your recipedb.sql on this database
* Edit Configuration DB Configuration Settings /Config/database.php to match your database settings. 
* Edit /temp folder in the application writable for web user. example: - sudo chown -R apache.apache tmp If you don't make /tmp writable by the web user the app will not run! 
* For File uploads: - mkdir /webroot/files/recipe - sudo chown . /webroot/files/recipe 
* Run ./Console/cake schema update

**Comment by upsidedowncake** [comment]
Thanks for your reply.  I'll try to run through the steps this week and see how it goes.  I'm very novice at MySQL but will try to give it a go.

**Comment by nazgul26** [comment]
No update, hope it all went well.
