### ISSUE TITLE
Minor Bugs: Project Development

### ISSUE THREAD

**Issue by jason-sara** [nazgul26/PHPRecipebook#58]
Hello,

I apologize in advance if this is not the appropriate forum to broadcast such a request or if my request violates some kind of rule or policy.  I was unable to find contact information for any of the project developers so I am leaving my request here.

I installed PHPRecipebook a few months back (July '17 time frame) and have enjoyed using the software.  I have found a few little bugs that make using the software a little cumbersome for folks a little less patient that myself (such as my wife).  I would like to say for the record though that I find this particular piece of software very useful and, for the most part, very easy to use.  I think that it has a whole lot of potential if a few of the bugs can be worked out.

I know that developing a community project like this takes time and resources (money).  While I am not a programmer myself, I would be happy help out with the project in any way I can (financial contributions, web hosting, testing, etc.) in order to help this project into a more mature form.

If anyone of the developers here is interested in taking me up on my offer, I would be more than willing to discuss the project's needs here or via e-mail or telephone.  Please respond as soon as is convenient.

Thank you,
Jason

**Comment by nazgul26** [comment]
Hi - It really is just me  in the developer pool for this project.  No worries on the issue posting as a question.  It is odd that GitHub does not have a message option.  

If you have minor bugs please feel free to the post them in this thread.  I have a couple improvements I want will be working on in the next month and could work in some additional fixes without much issue.  If the list is pretty big we can spin them out into separate issues.

Appreciate your offer of assistance and that you enjoy the software.   People using the software and seeing value in it is really what keeps me improving it and sharing back the changes. 

Testing out fixes and giving specific details on what works/doesn't is probably the most help I need.  I don't need any hosting or anything else that I can think of.  But if you see a void you can fill let me know.

Todd

**Comment by jason-sara** [comment]
Todd,

Thank you for getting back to me so promptly.  I read your posting a few days ago.  However, this is the first opportunity I've had to really sit down and type things out.

I guess the biggest issue I have is with the quantity conversion on the recipe entry form.  I have noticed that if you enter a fractional number, sometimes it converts it to a decimal number and sometimes it leaves it as a fraction.  If the program doesn't automatically convert it or if you forget (or are unaware of the need) to convert it to decimal form yourself, the program dumps that ingredient and all ingredients and other fields filled in from that point on.  If you convert it to a decimal number yourself or if the program converts it for you, then you don't have an issue.

Something that I would find useful, although I don't know how easy it would be to implement, is the ability to mark an ingredient as split.  What I mean here is that if your recipe calls for 3-1/2 cups of sugar but a half cup of it should be set aside to be used as a topping, it would be useful to be able to mark it as such.  I believe I understand why you chose not to allow duplicate ingredients and I am on board there.  However, it would be nice in cases like the one I mentioned above.  Perhaps as another example, splitting an egg and using the yolk in one part of the recipe and the white in another part of the recipe.  Here is a link to a recipe that I entered.  It would be nice to be able to annotate next to the ingredient in the ingredients list that 1/2 c of sugar and the egg whites should be used for the topping, if desired.  I chose not to create a separate (yet related) recipe for the topping in the linked recipe as it seemed to make more sense to do it the way I did it.  [Banana Pudding](http://recipebook.walterfamilywy.info/recipes/view/18)

Moving on, it would be nice to be able to have the list of ingredients available to all users (as opposed to only the individual user).  My goal with my implementation of your software is to create a family recipe program that all of my and my wife's family members can easily enter their recipes into.  I find it difficult to entice folks into entering recipes into the database when they have to go and recreate the wheel with their own list of ingredients.  Now, I do definitely see how having separate ingredient lists for each user could be useful in a "commercial" environment.  I do think, however, that the site administrator should be given that option (maybe an install option: select it once and you can never go back kind of thing or maybe maintain the private list but allow the site administrators/editors to maintain a list of publicly available ingredients).

I think the last thing that I have for now (I need to make a list as I am using the software so I can give more effective feedback :-) ) is on the menu planner.  It may just be my monitors, but I find it difficult to distinguish between breakfast, lunch, dinner, and dessert items based on the color code at the bottom of the screen.  On my computer all of the colors except for dinner look the same and dinner looks like it is color coded as lunch.  This could just be my cheapie monitor though.

I should get to entering a few more recipes this weekend and I will take some detailed notes.  Also, if you think you would find it helpful, I will create you an admin account or give you access to mine for testing/troubleshooting purposes.

Thank you for all of your help.

**Comment by jason-sara** [comment]
Todd,

I apologize for "spamming" here but I thought of a couple more things (feature wise).  It would be nice to be able to attach pictures in the directions area.  I see quite a number of food blogs where folks explain how to make the recipe in detail, adding pictures where necessary to clear up confusion or convey a point or simply to ensure to the person preparing the recipe that they are on the right track.

Also, it would be very nice to be able to edit the contents of a few of the drop-down menu fields on the fly (instead of just the ingredient fields).  For instance, being able to add items on the fly to the "Base Type" and "Ethnicity" fields would be super helpful.

Lastly, and then I think I'm done (for now at least)... I personally think it would be useful to split up the "Preparation Time" field into, perhaps, two different fields: one for preparation time and one for cook time.  With certain types recipes, namely slow cooker and bread maker type recipes, that preparation time can be deceiving.  If it only takes 15 minutes to prepare everything for the crock pot but then six hours to cook, I think that should be plainly visible to the user, without the user having to read through the recipe first.  This will help folks who are busy and don't have a lot of time to spend "preparing" meals make a distinction between prep-time intensive meals and cook-time intensive meals, if that makes any sense.

Thank you for listening.

**Comment by nazgul26** [comment]
Well that is for sure a lot of feedback. I think spinning out the fractions issue into an issue and fixing that would be first step.  The rest I need to think about best approach.  I will get some more time as the winter sets in to improve the software.

**Comment by nazgul26** [comment]
For the fraction conversion issue:  I have merged the fix by 'DeathStapler', if you can get that fix (edit.ctp) let me know if it takes care of the issue.  The fix seems like exactly like what you described.

**Comment by nazgul26** [comment]
For the split ingredients.  Would a 'Notes' field work?  Already have qualifier which goes before.  Notes would go after and probably be put in a tooltip or some special formatting to make it clear it is add-on info.  You would have a note option per ingredient.  What you think?

**Comment by jason-sara** [comment]
Todd,

I think that having a notes field will work nicely, especially given that there is a short character limit in the qualifier field.  When you say that "Notes...probably be put in a tooltip or some special formatting...", what kind of formatting, exactly, were you thinking.  I am more of a visual person so having a frame of reference would help me tremendously.  Link to a similar field on a website somewhere?

@DeathStapler Thank you for the fractions fix.  I will get it implemented this weekend and verify it corrects my problem.

**Comment by nazgul26** [comment]
The note will be in brackets [, ].  Simple but should be enough.  

![image](https://user-images.githubusercontent.com/8339440/34463691-2b47cb80-ee32-11e7-8cda-5b14dc26cf12.png)

Get latest and add new column
ALTER TABLE ingredient_mappings ADD `note` VARCHAR(255);   

Make sure you clear your app/tmp files after that change.  Otherwise it will not see the new column.

**Comment by jason-sara** [comment]
Todd,

Hello.  Thank you for your time.  I appreciate your willingness to help us out to this point.  I performed a git pull to update the appropriate files.  I have added the column to the table ingredient_mappings, as per your instructions.  That went off without a hitch.  I also went into the tmp folder and executed the command rm -R * to remove all files from the tmp folder.

After performing these steps I attempted to browse to the website but got a totally blank page.  Any suggestions?  Maybe I misunderstood your instructions?

*** Afterthought: I should add that I am hosting my website on my own server here at home.  So, if you would like I could set you up with SSH access to look around and make sure I haven't messed up anything simple.

**Comment by jason-sara** [comment]
Todd,

Please disregard my last posting.  I figured it out.  It would be nice for everyone involved here if I could learn to read. :smile:

**Comment by jason-sara** [comment]
After performing the update correctly (finally) it seems as though the edit recipe page isn't scaling properly.  The optional check box column is cut off.  If you scroll to the right it appears, but it then cuts off the left had side of the page, up to the delete icon.  Not a huge deal but a little annoying.  See the attached files.
![left side cut off](https://user-images.githubusercontent.com/32228677/35117877-445518ac-fc4d-11e7-8aa5-784aed5337c4.png)
![right side cut off](https://user-images.githubusercontent.com/32228677/35117878-449537c0-fc4d-11e7-94d2-30e94d0b228a.png)

**Comment by nazgul26** [comment]
Yes.  I agree the sizing is not quite right. I am think I am going to make the 'Note' a button instead that will show a dialog to add the note.  That will give back the space and should let me put back the spacing as it was before.

**Comment by jason-sara** [comment]
That sounds good.  I would assume it would still show up the same way it does now when viewing/printing the recipe?

**Comment by nazgul26** [comment]
Yes.  Will probably change to tables instead of divs, but the look should be just about the same.

**Comment by nazgul26** [comment]
Changes are in.  Layout is cleaned up a bit on showing the note.  By putting in a dialog the sizing can be put back the way it was.  There is an odd bug where the dialog jumps to the bottom of the page.  I will work that under a new issue.  Now that I notice it does that for all dialogs it is annoying enough for me to want to track down.
