### ISSUE TITLE
Can't export on demo site

### ISSUE THREAD

**Issue by rodrigoesborges** [nazgul26/PHPRecipebook#59]
When trying to export recipe, I get:

Error: ExportController could not be found.

Error: Create the class ExportController below in file: phprecipebook/Controller/ExportController.php

stack trace:
APP/webroot/index.php line 112 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by Luegengladiator** [comment]
Same here after clean Installation

**Comment by elsphinc** [comment]
Same. Any luck with a solution

**Comment by smokinjo** [comment]
Hello,

I get the same error as rodrigoes did.

I am looking to export recipes to share with others.  This could be n one of the common recipe formats like mealmaster, since phprecipebook imports it already.

I look forward to any solutions, and am willing to help if needed.
