### ISSUE TITLE
Fractions Not Updating in Quantity Fields

### ISSUE THREAD

**Issue by DeathStapler** [nazgul26/PHPRecipebook#60]
Hi,

This is in reference to #58 by @jason-sara, which talked about the issues with fractions.  

> I have noticed that if you enter a fractional number, sometimes it converts it to a decimal number and sometimes it leaves it as a fraction. 

I had noticed this issue for a while now. I never really looked at it until it happen when I was making some pumpkin cookies and my wife noticed that they tasted a little different.  I compared the original to what I had in PHP Recipe Book and noticed the fractions were missing from all the ingredients.

This is what I had to update the javascript in the following file to make it work properly.

[PHPRecipebook/View/Recipes/edit.ctp](https://github.com/nazgul26/PHPRecipebook/blob/master/View/Recipes/edit.ctp) (Lines 22-26)
```php
$('#ingredientsSection .fraction input').each(function() {
   $(this).change(function() {
      fractionConvert($(this), "<?php echo __("Entered value is not a number/fraction, please try again.");?>");
   });
});
```

to this:
```php
$('#ingredientsSection').on("change", ".fraction input", function() {
   fractionConvert($(this), "<?php echo __("Entered value is not a number/fraction, please try again.");?>");
});
```

This is where I found the solution: https://stackoverflow.com/questions/18356216/jquery-on-only-works-once

**Comment by DeathStapler** [comment]
I created a pull request (#61) to address this and a couple other issues.

**Comment by nazgul26** [comment]
Thanks for the fix, appreciate it. It is merged and will be in next release.
