### ISSUE TITLE
Free-text search

### ISSUE THREAD

**Issue by ilveroluca** [nazgul26/PHPRecipebook#69]
The search box currently only does a case-insensitive search on the recipe name.  I think it would be useful to have it search over the recipe's name and ingredient names, and perhaps even the descriptions.  This would also make "Find by Ingredient" redundant, simplifying usage.

**Comment by nazgul26** [comment]
That wide a search will return a lot of less relevant search results.  At that point we would need to rank their relevance and it quickly becomes a feature that a very high cost.  

In an early version of the recipe database I had a advanced search page that allowed searching a lot.  But I find a rarely used it and it was a complicated page that just cluttered up things. So on the rewrite I went with a simple context search instead.  

Not saying I am completely against a deeper search, but it has to be simple and elegant.
