### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by smccloud** [nazgul26/PHPRecipebook#70]
I'm following the git install instructions and after everything is setup I get the following error when I try to access the site for the wizard.  Any ideas?
`Unable to configure the session, setting session.save_path failed.`

**Comment by nazgul26** [comment]
What version of PHP are you using? 

https://stackoverflow.com/questions/19004460/cakephp-error-unable-to-configure-the-session-setting-session-auto-start-faile

Lots of options suggested in that thread.  The cakePHP version of PHPRecipebook is 2.9 so upgrading won't be one of the options you have to try.
