### ISSUE TITLE
Ingredients without an amount

### ISSUE THREAD

**Issue by rettenbs** [nazgul26/PHPRecipebook#72]
Hi,

Some recipes have ingredients (e.g. species) which you do not really measure because you just add them depending on the taste. Would be nice to specify such ingredients without artificially selecting the amount.

Best,
Sebastian

**Comment by ilveroluca** [comment]
Personally, I generally specify "1 pinch" or "1 bunch" for this type of ingredient.  Units and bunches aren't well-defined units so it's really like not specifying a measurement at all :-)

**Comment by nazgul26** [comment]
Yes.  I use pinch as the 'to taste option'.  Not having a numeric value in the Database would introduce a lot of down stream issues.  The shopping cart would freak out.

I am adding a new field to ingredient called 'notes' and that could help you add some more direction like 'to taste'.

**Comment by rettenbs** [comment]
We can use 0 as a special quantity without breaking anything. #73 hides the quantity and the unit in the recipe view if it is set to 0. The offline shopping cart sould work in a similar way. I am not sure about online shopping since I am not using it.
