### ISSUE TITLE
After adding a new recipe, take user to "view recipe" page

### ISSUE THREAD

**Issue by ilveroluca** [nazgul26/PHPRecipebook#76]
After the user submits a new recipe the system currently goes to the recipe list and shows a little "pop-up" in the upper right corner.  I think it would be more functional to take the user to the "View recipe" page, so that the user can easily verify that everything was inserted correct, and have concrete confirmation that the operation was successful.

**Comment by nazgul26** [comment]
I agree.  No idea why I didn't do this sooner. Changed and will be in next release (soon) of pull latest code.
