### ISSUE TITLE
Schema update problem upgrading to 5.1.4

### ISSUE THREAD

**Issue by ilveroluca** [nazgul26/PHPRecipebook#77]
I'm trying to update my installation to the latest release.  When running

    ./Console/cake schema update

The command generates `ALTER` statements with a syntax error:

    Updating Database...
    attachments: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
    LINE 26:  ALTER COLUMN "tableParameters" TYPE ,

This happens for a number of tables, but always with the `tableParameters` column.  Here's an example:

    ALTER TABLE "public"."vendors" 
        ADD COLUMN "request_type" varchar(10) DEFAULT 'GET',
        ADD COLUMN "format" varchar(255) DEFAULT NULL,
        ALTER COLUMN "id" TYPE  serial ,
        ALTER COLUMN "id"  SET NOT NULL,
        ALTER COLUMN "id"  DROP DEFAULT,
        ALTER COLUMN "name" TYPE  varchar(64),
        ALTER COLUMN "name"  SET NOT NULL,
        ALTER COLUMN "name"  DROP DEFAULT,
        ALTER COLUMN "home_url" TYPE  varchar(255),
        ALTER COLUMN "home_url"  DROP NOT NULL,
        ALTER COLUMN "home_url"  DROP DEFAULT,
        ALTER COLUMN "add_url" TYPE  varchar(255),
        ALTER COLUMN "add_url"  DROP NOT NULL,
        ALTER COLUMN "add_url"  DROP DEFAULT,
        ALTER COLUMN "tableParameters" TYPE ,
        ALTER COLUMN "tableParameters"  DROP DEFAULT;

**Comment by ilveroluca** [comment]
Oh!  I should add:  I'm updating from version 5.1.1 and I'm running with PostgreSQL 9.6.

**Comment by ilveroluca** [comment]
I can add some new info to this issue.

With PostgreSQL version 11 and PHPRecipebook version 5.1.5 now.

I create a brand new DB schema with `./Console/cake schema create`.
I then try to update it with `./Console/cake schema update`.

I would expect this to be a no-op.  Instead:

I get a bunch of errors as Cake tries to compare the database to the desired schema:
```
Comparing Database to Schema...
Notice Error: Undefined index: tableParameters in [/usr/local/apache2/htdocs/phprecipebook/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/Database/Postgres.php, line 546]

Notice Error: Undefined index: type in [/usr/local/apache2/htdocs/phprecipebook/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/Database/Postgres.php, line 857]

Notice Error: Undefined index:  in [/usr/local/apache2/htdocs/phprecipebook/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/Database/Postgres.php, line 857]

...
```

Cake then wants to alter all tables, and if I let it try it results in the same error for every table:
```
Updating Database...
attachments: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 26:  ALTER COLUMN "tableParameters" TYPE ,
```

Full output available in this gist:  https://gist.github.com/ilveroluca/71568d7f3631be96b0d322d1ed02e3c7

**Comment by nazgul26** [comment]
Could you try remove the tableparam line from each table definition in schema.php?

I am updating the CakePHP 3.9 and that should make fix up the migration script if you can wait.

**Comment by nazgul26** [comment]
Figured this out, had some value it did not like in there.  Resolved in v6.
