### ISSUE TITLE
Error: The requested address 'recipes/view' was not found on this server.

### ISSUE THREAD

**Issue by GaneshKandu** [nazgul26/PHPRecipebook#78]
Hi,

Getting Error in [PHPRecipebook 5.1.4](https://github.com/nazgul26/PHPRecipebook/releases/download/5.1.4/phprecipebook-5.1.4.tar.gz) while saving ```recipes``` from ```recipes/edit``` url

![screenshot-webuzo web-2018-04-24-12-54-00](https://user-images.githubusercontent.com/12833130/39172580-afb7e108-4791-11e8-9ec1-898fa5da1af9.png)

Error Log
[error.log](https://github.com/nazgul26/PHPRecipebook/files/1941390/error.log)

php 5.4
mysql 5.5.53

**Comment by nazgul26** [comment]
In your error log it says: [NotFoundException] Invalid recipe.

Is this a new recipe or after save on an existing?  

In this release it was changed to redirect to view recipe after editing.

**Comment by GaneshKandu** [comment]
its a new recipe
can you check and confirm this on php 5.4
its working on php 5.6

**Comment by hhankj2u** [comment]
I got the same error on PHP 5.6.33

**Comment by nazgul26** [comment]
Fixed checked in and put in release 5.1.5 .
