### ISSUE TITLE
Installing from git

### ISSUE THREAD

**Issue by zasmth** [nazgul26/PHPRecipebook#8]
Everything works fine when I upload the .tar.gz for 5.0.1 from the releases page.
But, when I clone the repository from git and follow the instructions, I can never make it to where index.php loads. Am I doing something wrong, or does this relate to issue https://github.com/nazgul26/PHPRecipebook/issues/3?

I'm using Ubuntu 14.04, Apache 2.4.7, CakePHP 2.6.2

Some of the errors in the apache error log are:

PHP Warning:  include(/var/www/html/recipe/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/recipe/webroot/index.php on line 97

PHP Warning:  include(): Failed opening '/var/www/html/recipe/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/recipe/webroot/index.php on line 97

PHP Fatal error:  CakePHP core could not be found. Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php. It should point to the directory containing your /cake core directory and your /vendors root directory. in /var/www/html/recipe/webroot/index.php on line 104

PHP Warning:  include(/var/www/html/recipe/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/recipe/webroot/index.php on line 97

Thanks!

**Comment by nazgul26** [comment]
You need to run composer in the cloned directory.  You are missing CakePHP library and that is what all the errors are about. I have release 5.0.3 so if you still have issues you can grab that.

**Comment by zasmth** [comment]
I ran composer install in the cloned directory. 

I received confirmation:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
- Installing composer/installers (v1.0.21)
  Loading from cache
- Installing cakephp/cakephp (2.6.2)
  Loading from cache
- Installing josegonzalez/cakephp-upload (1.1.1)
  Loading from cache

Generating autoload files

Is this what you are talking about?

**Comment by nazgul26** [comment]
Yes.  Assuming then that did not resolve the issue.  The other thing to try is clearing out the files in the tmp folder for the app.
