### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by Luegengladiator** [nazgul26/PHPRecipebook#80]
In the last days I had to upgrade to php7. Now the DB-Connection can not be established:
CakePHP is NOT able to connect to the database.
error Message:Database connection "Mysql" is missing, or could not be created.

the corresponding package php7.0-mysql is installed

**Comment by nazgul26** [comment]
Have you confirmed the mysql module is loaded in apache/php?  Look in your php.ini file to ensure it is being loaded.  Also confirm that you can still login to MySQL using the CLI.  I know that for me upgrading MySQL has reset the root password.  And finally confirm that your MySQL instance is running on a port or socket and update the config to use what works.  Those are my best guesses.

**Comment by Luegengladiator** [comment]
Sorry my fault.
I messed up the database.php during php-upgrade and Recipebook upgrade.
