### ISSUE TITLE
Restaurants not working

### ISSUE THREAD

**Issue by dpejcha** [nazgul26/PHPRecipebook#81]
The Restaurants view has errors regarding undefined variables. File View/Restaurants/index.ctp looks like it may have been copied from the corresponding file for Recipes, but the changes to make it a view for Restaurants is incomplete - code is referring to a non-existent variable "recipe", and the tooltip for the address popup has a title of "Add More items for this ingredient".

**Comment by nazgul26** [comment]
Fixed with latest check-in to Restaurants/index.ctp, will be in next release in a couple months.
