### ISSUE TITLE
Upgrade from 5.0.11 to 5.1.5 getting errors "Notice (8): Undefined index: note [APP/View/Recipes/view.ctp, line 169]"

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#82]
I moved my PHPRecipebook to a new server and am getting this error:
`Notice (8): Undefined index: note [APP/View/Recipes/view.ctp, line 169]`
The error appears once for each ingredient in the recipe, but the full recipe does show after the list of errors.
The message in the error is:
`include - APP/View/Recipes/view.ctp, line 169
View::_evaluate() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php, line 963
Dispatcher::_invoke() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 113`
![recipe](https://user-images.githubusercontent.com/16404870/47624715-8e4ef680-dadc-11e8-9415-7c04be99f62b.png)

**Comment by withanhdammit** [comment]
Sorry, I upgraded it right after I moved it and thought it was related to the move, but it actually works fine with 5.0.11, but 5.1.5 shows the index errors.  Is there a command I need to run to update the database so it knows that?  I didn't see anything in the readme about a schema update.

**Comment by jsjsjsjs** [comment]
Same here after updating master.

**Comment by nazgul26** [comment]
Looks like the new 'note' column is missing from ingredient mapping table.  Try

ALTER TABLE ingredient_mappings ADD COLUMN `note` VARCHAR(255);

The schema up should also update that as well:

./Console/cake schema update

**Comment by jsjsjsjs** [comment]
Checked that:

```
MariaDB [recipedb]> describe ingredient_mappings;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| recipe_id     | int(11)      | NO   |     | NULL    |                |
| ingredient_id | int(11)      | NO   |     | NULL    |                |
| quantity      | float        | NO   |     | NULL    |                |
| unit_id       | int(11)      | YES  |     | NULL    |                |
| qualifier     | varchar(32)  | YES  |     | NULL    |                |
| note          | varchar(255) | YES  |     | NULL    |                |
| optional      | tinyint(1)   | YES  |     | NULL    |                |
| sort_order    | int(11)      | YES  |     | NULL    |                |
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
+---------------+--------------+------+-----+---------+----------------+
9 rows in set (0.01 sec)

```
Any cache for the schema maybe that needs to be deleted?

**Comment by nazgul26** [comment]
Yes - from the readme - 

Upgrades in 5.x Series

Between releases you can update your database by running

    Get latest release (git or Release download).
    ./Console/cake schema update
    **removing all files from ./tmp/cache/models**

If you are pulling from git then you can leave the 'empty' file.

**Comment by jsjsjsjs** [comment]
Checked that; deleted cache. Issue still there.
I did a fresh install with using the existing database. All fine. 

Git is clean, no local changes. Pretty strange. My guess: cakePHP.

From my perspective this can be closed. I'll try to figure out the actual root cause on my system. Just curiosity...
