### ISSUE TITLE
Getting Blank Page on URL/import

### ISSUE THREAD

**Issue by GaneshKandu** [nazgul26/PHPRecipebook#83]
Hi @nazgul26

I am Getting Blank Page on URL/import in PHPRecipebook 5.1.5
Downloaded from Github [phprecipebook-5.1.5.tar.gz](https://github.com/nazgul26/PHPRecipebook/releases/download/5.1.5/phprecipebook-5.1.5.tar.gz)

Dashboard > recipes > import

**Comment by GaneshKandu** [comment]
Also want to know
Under What Licence **PHPRecipebook** is released ?

**Comment by nazgul26** [comment]
GPL V3.  The Import code is a work in progress.
