### ISSUE TITLE
How to install on Windows10?

### ISSUE THREAD

**Issue by LINKn8r** [nazgul26/PHPRecipebook#84]
Is there a way to install on this PHPRecipebook onto a Windows10 machine?  I mean a way that common folk can understand and execute?
I have had nothing but problems for the last several weeks trying to get PHPRecipebook up and running on my machine at home.  Let me quantify that.  I am not a web developer.  I am not a programmer or code writer.  I'm just a guy who want to use this tool in my home to track my recipes on my localhost webserver.  I'm not completely computer illiterate either.

I had an earlier version (maybe 2.x or 3.x) up and working on a website that I maintained on a linux server.  As I recall, install and set-up was pretty straight forward.  Now, it seems like transferring things to Windows way of life is almost impossible.

I have successfully installed Apache 2.4.
I eventually was able to install PHP 7.2.12 with no errors.
I eventually somehow got CakePHP to function.
I was able to create the phprecipebook database on PostgreSQL.
I believe mod-url-rewrite is working.
So after a lot of frustration and time wasted, I was able to get the PHPRecipebook configuration page to come up.  I seemed to have breezed right past the database configuration page, despite the only commands listed not being Windows recognized commands:
[ Create the schema -
sudo ./Console/cake schema create
* Answer Y to drop, Y to create
Import sample ingredients (optional) -
Config/SQL/sample_ingredients.sql(optional)
Edit the configuration file to set your Email Server/Account
./Config/email.php ]
However, I could not import the sample ingredients, and I think I configured the email file correctly, but I'm not quite sure.

Now, my latest roadblock is getting past the password configuration page.  I tried the "user@localhost" email as well as my own email.  I cannot get past this error.
The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

I will gladly accept any help that can be offered.
Also, it would be extremely awesome if there were detailed instructions for installations on Windows by your average Joe.

Thanks much.

**Comment by nazgul26** [comment]
The error message you are getting could be an infinite redirect loop.   I am not sure what you could try next.  Sounds like you got really far in the process and fixed overcame quite a few things.

The only thing I can suggest is to consider Docker.  We could get a Docker image setup for PHPRecipeBook if no-one has already done so and then you could run on Windows10 in a Unix Docker container.  I have just recently started doing this for some other Unix products I use with good results.

Let me know if you want to give this approach a try and I can try it out as well.  Or maybe another user has successfully done this. I saw a issue request to add Docker.

**Comment by LINKn8r** [comment]
Thanks Todd. I may consider using Docker.
However, in the mean time, are there any installation logs or other logs I can review to help troubleshoot?
I found this in my database logs:
2018-12-09 17:36:17 CST [11056]: [1-1] user=postgres,db=phprecipebook,app=[unknown],client=::1 LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

	
2018-12-09 17:36:17 CST [11056]: [2-1] user=postgres,db=phprecipebook,app=[unknown],client=::1 LOG:  unexpected EOF on client connection with an open transaction
2018-12-09 17:36:28 CST [6256]: [1-1] user=postgres,db=phprecipebook,app=[unknown],client=::1 LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

	
2018-12-09 17:36:28 CST [6256]: [2-1] user=postgres,db=phprecipebook,app=[unknown],client=::1 LOG:  unexpected EOF on client connection with an open transaction

So, something definitely on the PHPRecipebook side is closing the connection. I'm hoping to identify what is the cause of the error.

Thanks again.

**Comment by nazgul26** [comment]
Use the Heroku Deploy option.  Very easy/fast way to get running if you don't have Linux env.
