### ISSUE TITLE
Next to no Windows10 support

### ISSUE THREAD

**Issue by LINKn8r** [nazgul26/PHPRecipebook#85]
This recipe book software would be totally awesome if an average Joe could install it. Unfortunately, you need to have a degree in computer programming/PHP/database/cake/linux environment to get it working. I guess paying $80 bucks and up for a good working recipe book becomes worth it to be able to use anything.

A Windows installer (that maybe asks a few questions about my web server/database/environment) would be most useful. Again, if an average joe could install and use this, you would have a wonderful program here. However, as it looks to have the intended audience of a developer in mind, I'll have to give it zero stars and move on to something I can actually use. Really is a shame though, as I recall it being one of the best several years ago.

**Comment by nazgul26** [comment]
Please use the Heroku Deploy option that should get you up and running fast.
