### ISSUE TITLE
Error claiming that database table does not exist

### ISSUE THREAD

**Issue by Magnatolia** [nazgul26/PHPRecipebook#87]
Hi all,

The only step I couldn't do was to sudo the schema, so I used PhpMyAdmin and imported the schema_MySQL.sql file. I can now see all the tables. The 'recipes' table has a heap of pre-defined columns.

I've updated the database.php to the table name, But, when I load PhpRecipeBook, I get a number of undefiend variable errors along the top, some invalid argument errors in the recipe box. And the most telling error is in the centre: "Error: Table recipes for model Recipe was not found in datasource default."

My database is called "recipedb". These are the database config settings:

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'root',
		'password' => '',
		'database' => 'recipedb',
		'prefix' => '',

Thanks!

**Comment by nazgul26** [comment]
Try clearing out your ./tmp/cache/models files.
