### ISSUE TITLE
Can't successfully install

### ISSUE THREAD

**Issue by GregLeonhardt** [nazgul26/PHPRecipebook#88]
I have been trying to install for a couple of days now and can't get it running.  I have tried with Debian 9, Debian 8, Ubuntu 18 LTS and Ubuntu 16 LTS and they all fail in the same place.

After loading everything and connecting with the browser I click the 'New Install' link which fails with a 404 error on page address "http://localhost/phprecipebook/setup/database".

I see find anything in the tmp/logs directory.

Is there a linux version where the install is known to work?  If so I'll switch to it and try again.

Also composer is complaining about [ "name": "PHPRecipeBook", ] in composer.json.  I changed it to  [ "name": "phprecipebook/phprecipebook", ]  and updated the install but it didn't make any difference.

**Comment by nazgul26** [comment]
I know it runs on Ubuntu 18.  I don't think your Linux distro/version is the issue.

If you are running from a release you won't have to worry about Composer, all the libraries should be included.  

A 404 would make me think maybe Apache is not serving up the content from the location you are expecting.  If you have a default Apache install then things should be at /var/www/html/phprecipebook.  Try then just pulling up: http://localhost/phprecipebook and see what happens.

Be sure to set the permissions on /var/www/html/phprecipebook/tmp.  Making that tmp writable by apache is critical to things running.

**Comment by GregLeonhardt** [comment]
I believe that URL rewriting is at the core of whatever is going wrong.  That's why I have switched to so many different distributions.  I have been following the install instructions.  I even went to the extreme of giving ownership of the whole phprecipebook directory tree to www-data without any forward progress.

I did a fresh install of Ubuntu 18 but it is failing exactly the same as every other distributions I have used.  I suppose I should note that I am doing all my testing on a VirtualBox virtual machine though I have a hard time believing it has anything to do with the failure.

The first page displayes just fine, the issue shows up when I click the new install link.

I looked over the "Help me configure it" page and changed /etc/apache2/apache2.conf to "AllowOverride All" from "AllowOverride None" and restarted apache.  Unfortunately it didn't change a thing.

It is probably frustration on my part speaking but I have to ask: Has anybody done a fresh install recently.  I'm thinking a support package or two has updated and is causing problems.

I attached a my cheat-sheet for the install with some install and runtime output.

[PHPRecipeBook.txt](https://github.com/nazgul26/PHPRecipebook/files/3796072/PHPRecipeBook.txt)

**Comment by nazgul26** [comment]
The warning message on first page from you text files indicates that you don't have mod-rewrite enabled/installed. 

https://hostadvice.com/how-to/how-to-enable-apache-mod_rewrite-on-an-ubuntu-18-04-vps-or-dedicated-server/

I did re-test my local Ubuntu version and things all appear fine.
