### ISSUE TITLE
Can't install on Debian 10: dependencies, sql incompatibilities, php incompatibilities, etc...  Details inside.

### ISSUE THREAD

**Issue by afc54** [nazgul26/PHPRecipebook#89]
This report comes from someone not very familiar with php or web server setup.
Thus, I took detailed notes and it took me a long time to figure out some of
the issues.  I'm now stuck at the SQL syntax incompatibilities.

Looking for any help, I found that the mailing list has been dead for years
and whatever forum posts are semi-modern (ie: not years old) seem to show that
no one is having such basic installation problems.

It would be very nice if there existed a gateway between all the fora
(sourceforge, github and wherever else I haven't found) and the mailing lists.
I much prefer mailing lists.

This is what I've done so far, on a Debian 10 system, completely up-to-date.
As can be seen below, the issues I have solved required a quite a long
series of steps.  Is this level of complexity expected?  Is this a case of the
dependencies having been upgraded in incompatible ways while phprecipebook
has stood still?

Installed git-all, dependencies and suggestions.
Got phpcomposer (https://getcomposer.org/download) based on the multiple steps
described there.

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

php composer.phar install

reported various problems, so installed

php-gd, mcrypt, php7.3-pgsql (since I'd like to try this with pgsql), cakephp.

Errors remain.

Per

https://www.techrepublic.com/article/how-to-install-mcrypt-for-php-7-2/

Installed the following Debian packages:

php7.3-dev, libmcrypt-dev, dependencies and suggestions.

Then sudo pecl install mcrypt-1.0.1

but this fails

WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update

which I did:

sudo pecl channel_update pecl.php.net

Then:

sudo pecl install mcrypt

Lots of output but this is significant:

----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/pear/temp/pear-build-rootynzNGX/mcrypt-1.0.3/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

The libraries have been installed in /tmp which will be wiped out at the next
reboot.

But then there was this:

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3" install
Installing shared extensions:     /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr/lib/php/20180731/
running: find "/tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3" | xargs ls -dils
11543346   4 drwxr-xr-x 3 root root   4096 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3
11678264   4 drwxr-xr-x 3 root root   4096 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr
11678265   4 drwxr-xr-x 3 root root   4096 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr/lib
11805375   4 drwxr-xr-x 3 root root   4096 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr/lib/php
11805376   4 drwxr-xr-x 2 root root   4096 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr/lib/php/20180731
11805377 204 -rwxr-xr-x 1 root root 207840 Jan 13 16:53 /tmp/pear/temp/pear-build-rootynzNGX/install-mcrypt-1.0.3/usr/lib/php/20180731/mcrypt.so

Build process completed successfully
Installing '/usr/lib/php/20180731/mcrypt.so'
install ok: channel://pecl.php.net/mcrypt-1.0.3
configuration option "php_ini" is not set to php.ini location
You should add "extension=mcrypt.so" to php.ini

But it appears that there are 3 versions of php.ini:

> locate php.ini
/etc/php/7.3/apache2/php.ini
/etc/php/7.3/cgi/php.ini
/etc/php/7.3/cli/php.ini
/usr/lib/php/7.3/php.ini-development
/usr/lib/php/7.3/php.ini-production
/usr/lib/php/7.3/php.ini-production.cli

> ls -l /etc/php/7.3/apache2/php.ini
-rw-r--r-- 1 root root 72294 Oct 26 10:14 /etc/php/7.3/apache2/php.ini
> ls -l /etc/php/7.3/cgi/php.ini
-rw-r--r-- 1 root root 72294 Oct 26 10:14 /etc/php/7.3/cgi/php.ini
> ls -l /etc/php/7.3/cli/php.ini
-rw-r--r-- 1 root root 71906 Oct 26 10:14 /etc/php/7.3/cli/php.ini

Added "extension=mcrypt.so" to all 3 files.

Re-ran:

php composer.phar install

and now the only problem that remains is:

 - This package requires php ^5.5.0 but your PHP version (7.3.11) does not satisfy that requirement.

Modified composer.json and composer.lock
(in phprecipebook-5.0.11/phpresipebook) and changed one line in each file
from php 5.5.0 to php 7.3.11,

       "php": "^7.3.11",

then re-ran

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php composer.phar install

This time the above error disappeared.  The deprecation warning is still
there and now there is a warning that the lock file is not up to date with
the latest changes in composer.json.  It is recommended that you run
'composer update'

It then said "nothing to install or update."

composer update is not found if I run that command from the shell.

Now I need to figure out how to either install the relevant files to where
a web browser can find them and run the whole thing or how to run the thing
in place (in ~/archives/phprecipebook...).  Entering file://<path>/index.php
in the browser does not work, it only opens an editor to look at the file.

Installed (via aptitude)

postgresql-11,  php-pgsql but given the mountain of problems and the fact
that there isn't a schema_PgSQL.sql file I figured I'd try with mysql first.

Create a database: (already in phprecipebook directory)

> cd Config/SQL
> sudo mysql -u root
MariaDB [(none)]> create database phprecipebook;
MariaDB [(none)]> quit;

sudo mysql phprecipebook < schema_MySQL.sql > output.tab

ERROR 1064 (42000) at line 99: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--picture MEDIUMBLOB,
    --picture_type VARCHAR(32),
    private BOOL NOT NULL,' at line 19

So this is where I'm stuck now.  I removed comments near this error, and it
seems that newer versions of MariaDB handle comments in a way that these are
fatal, but even after that I still get SQL syntax errors:

> sudo mysql phprecipebook < schema_MySQL.sql > output.tab
ERROR 1064 (42000) at line 122: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(`id`)
)' at line 10 

All the references to this type of error message that I found don't give me
a clue as to what the incompatibility is.  Line 122 (as the schema file is
now is marked below).

CREATE TABLE recipes (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    ethnicity_id INT REFERENCES ethnicities(id) ON DELETE SET NULL,
    base_type_id INT REFERENCES base_types(id) ON DELETE SET NULL,
    course_id INT REFERENCES courses(id) ON DELETE SET NULL,
    preparation_time_id INT REFERENCES preparation_times(id) ON DELETE SET NULL,
    difficulty_id INT REFERENCES difficulties(id) ON DELETE SET NULL,
    preparation_method_id INT REFERENCES preparation_methods(id) on DELETE SET NULL,
    serving_size INT,
    directions LONGTEXT,
    comments MEDIUMTEXT,
    source_id INT REFERENCES sources(id) ON DELETE SET NULL,
    source_description VARCHAR(200),
    modified DATE,
    image VARCHAR(255),
    image_dir VARCHAR(255),
    private BOOL NOT NULL,
    system VARCHAR(16) DEFAULT 'usa' NOT NULL,
    user_id INT NULL REFERENCES users(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
        PRIMARY KEY (id)
);

CREATE TABLE attachments (          <--- this is line 122
    id INT NOT NULL AUTO_INCREMENT,
    recipe_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    `name` VARCHAR(32) NOT NULL,
    `attachment` VARCHAR(255) NOT NULL,
    `dir` VARCHAR(255) DEFAULT NULL,
    `type` VARCHAR(255) DEFAULT NULL,
    `size` int(11) DEFAULT 0,
    sort_order INT
    PRIMARY KEY (`id`)
);

Finally, when I first cloned phprecipebook, per the README file I used:

git-clone  git://phprecipebook.sourceforge.net/

Just in case the code has been updated recently I tried

git pull  git://phprecipebook.sourceforge.net/

but it gives this error:

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

The README file says installing from a git-clone takes more work up front but
is easier later.  Obviously I'm not doing something right.  Help!

**Comment by nazgul26** [comment]
Sorry for your frustration getting this going.  I would suggest using a 'Release' version of PHPRecipebook that has all the Composer deps downloaded for you.  That way you can skip that step.

https://github.com/nazgul26/PHPRecipebook/releases

I would also suggest you get PHP successfully running before you start.  Use a install guide like:
https://computingforgeeks.com/how-to-install-latest-php-on-debian/

You should not be needing to build from source. If you are there is a sign things have left the rails.

**Comment by afc54** [comment]
Thanks for replying.  I downloaded phprecipebook-5.1.5.tar.gz and extracted
it to /var/www/html.

Per the previous posting, I had installed the dependencies (which was not
trivial) and created the database.

cd /var/www/html/phprecipebook
sudo chown -R www-data:www-data tmp
mkdir webroot/files/recipe
sudo chown www-data:www-data webroot/files/recipe

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php

This last one said Composer (version 1.9.3) successfully installed to:
/var/www/html/phprecipebook/composer.phar
Use it: php composer.phar

php composer.phar install

came up with an error:

[ErrorException]
  file_put_contents(/var/www/html/phprecipebook/Vendor/composer/autoload_static.ph
  p): failed to open stream: Permission denied

Ran

sudo php composer.phar install

and this time it worked.  Got this output:

Deprecation warning: Your package name PHPRecipeBook is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

I suspect  I need to set some user id/group id (autoload_static.php is
root.root) but what? Would a recursive

sudo chown -R www-data:www-data /var/www/html/phprecipebook

be what's needed?

Going to localhost/phprecipebook in the browser brings up the "Welcome to
PHPRecipeBook 5.0" page but it starts with this:

Notice (8): compact(): Undefined variable: etagMatches [APP/Vendor/cakephp/cakephp/lib/Cake/Network/CakeResponse.php, line 1171]

Notice (8): compact() [function.compact]: Undefined variable: timeMatches [APP/Vendor/cakephp/cakephp/lib/Cake/Network/CakeResponse.php, line 1171]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

And then the first error I see is:

  CakePHP is NOT able to connect to the database. Check that:
  1. Installed the appropriate PHP db module (i.e. php-mysql, php-pgsql)
  2. The database has been created and you can connect to it
  3. Have the correct username password in database.php config file

php-mysql 2:7.3+59 is installed.
the database was created:

sudo mysql -u root
MariaDB [(none)]> create database phprecipebook;
MariaDB [(none)]> quit;

The username is root with no password, just like in database.php.

But I still couldn't access the database.  Based on something I had tried for
another program that accesses mysql, tried this:

sudo mysql -u root
MariaDB [(none)]> grant all privileges on phprecipebook.* to 'www-data'@'localhost' identified by 'www-data' with grant option;
MariaDB [(none)]> grant all privileges on phprecipebook.* to 'www-data'@'%' identified by 'www-data' with grant option;
MariaDB [(none)]> flush privileges;
MariaDB [(none)]> quit;

But it didn't work either.  Given that the user is specified as root in
database.php, did the same but instead of 'www-data' used 'root' and then
I couldn't access mysql at all, even as root.  After some research found this:

https://stackoverflow.com/questions/41645309/mysql-error-access-denied-for-user-rootlocalhost

and per the instructions therein had to:

vi /etc/mysql/my.cnf

added a section 

[mysqld]
skip-grant-tables

and restarted mysql:

/etc/init.d/mysql restart

This is probably not a good idea but it gave me back access and now
phprecipebook can connect to the database.

What is the proper fix for this?  It seems that skipping the grant tables
eliminates any security.  Tried the second part described there:

Alter user 'root'@'localhost' identified by ''; (I didn't have a root password
before and I don't want to add the complication of one now) but
mysql came back with:

ERROR 1290 (HY000): The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement

Than phprecipebook said:

"URL rewriting might not properly configured on your server." 

Note that there is a missing "be" in that sentence, it should be

"URL rewriting might not BE properly configured on your server." 

So I clicked on the "Help me configure it." link

Modified /etc/apache2/apache2.conf.  Changed

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

to:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

and

/etc/init.d/apache2 restart

Reloading localhost/phprecipebook now looks quite different but I still get
the warning message about URL rewriting.  The .htaccess files look mostly
the same as the ones described in the help link, so I continued to "New Install"

This page also has all the "Notice (8): compact()" errors.

When attempting to save the admin user and password, in addition to many
"Notice (8): compact()" errors I get (in a yellow field):

array(
        'email' => array(
                (int) 0 => 'email',
                (int) 1 => 'email'
        )
}

/phprecipebook/Controller/SetupController.php (line 40)

and I can't proceed.

Earlier I tried to import the schema outside of phprecipebook but encountered
the same SQL syntax error I described in the first post, in the same place:
line 122, so it's possibly still an issue.

So, so summarize: plenty of undefined variables in cakePHP, the show stopper
of not being able to proceed after entering the admin user, password and
email, my work-arounds that could be dangerous security-wise and the SQL syntax
error.  I would welcome any pointers as to how to fix all this.  Thanks!

**Comment by afc54** [comment]
compact() function and undefined variables (in cakephp)

Notice (8): compact() [function.compact]: Undefined variable: subject [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128]

This error is apparently caused because cakephp has not kept up with the
latest php:

  7.3.0 compact() now issues an E_NOTICE level error if a given string
  refers to an unset variable. Formerly, such strings have been silently
  skipped.

7.3 is what comes with Debian 10/stable.  Strangely, the cakephp web site
says "7.4 supported".  One would think that if 7.2 is the minimum required
and 7.4 is supported, that 7.3 would work.

After entering user name, password and email the error message is:

The user could not be saved. Please, try again.

but no matter how many times I try, I can never get beyond this point.


Notice (8): compact() [function.compact]: Undefined variable: radioOptions [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/FormHelper.php, line 1082]

Notice (8): compact() [function.compact]: Undefined variable: dateFormat [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/FormHelper.php, line 1082]

Notice (8): compact() [function.compact]: Undefined variable: timeFormat [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/FormHelper.php, line 1082]

This set of 3 error messages happens for each of: user name, password and
email address.  They are caused by the same issue in compact().

I have now automated a bit the installation process.  What I have done
beforehand that might or might not have been necessary:

Added

<FilesMatch \.php$>
SetHandler application/x-httpd-php
</FilesMatch>

to the end of /etc/apache2/apache2.conf

Installed the extension mcrypt (see first post in this thread)

The database has been created, but thanks to my inept attempt to figure
out access permissions (see second post) I'm now running mysql with the
skip-grant-tables option.


#
# This script attempts to automate the installation of phprecipebook on
# Debian 10/stable.
#
cd /var/www/html
#
# The following creates /var/www/html/PHPRecipebook
#
sudo git clone https://github.com/nazgul26/PHPRecipebook.git
#
# For ease of editing. I'll have to figure out what the proper user/group
# and permissions are.
#
sudo chown -R afc:afc PHPRecipebook
#
# Now: the steps prescribed
#
cd /var/www/html/PHPRecipebook
sudo chown -R www-data:www-data tmp
#
# -p because intermediate directory doesn't exist
#
mkdir -p webroot/files/recipe
sudo chown www-data:www-data webroot/files/recipe
#
# Install composer
#
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php composer.phar install
php -r "unlink('composer-setup.php');"


After this, pointing the browser to

localhost/PHPRecipebook

brings up the setup pages but I get stuck at the user name/password/email
address as described above.  Since I really don't know php, any hints as to
what the proper place is to declare/define/set/unset/etc... those undefined
variables would be welcome.

**Comment by nazgul26** [comment]
If you can't login and the only other issue is the E_NOTICE (not ERROR level) then I would suggest you check that you inserted the default user/password seed data.

**Comment by afc54** [comment]
On Sat, Feb 22, 2020 at 08:27:51AM -0800, Todd Rogers wrote:
>    If you can't login and the only other issue is the E_NOTICE (not ERROR
>    level) then I would suggest you check that you inserted the default
>    user/password seed data.

I didn't insert anything beyond the user name, password and email
address.  I don't even know what the "default user/password seed data"
is and where this is inserted.  I tried entering an empty password and
the system told me that it couldn't be empty.  I tried a user name
with only lower case letters and it also failed.  In a yellow field at
the top there was this:

array(
	'email' => array(
		(int) 0 => 'email',
		(int) 1 => 'email'
	)
)

/PHPRecipebook/Controller/SetupController.php (line 40)

This line in the code is:

} else {
   debug($this->User->invalidFields());  <--- this is line 40
   $this->Session->setFlash(__('The user could not be saved. Please, try again.'));
                }

So it looks like it's doing some validity check on the email address.
The mailer (exim4) on the system I'm setting this in is set up for
local delivery only, so it should have accepted afc, afc@localhost,
afc@<machine-name>.<internal domain as configured in exim4> but it only
worked when I entered my external email address that I interact with
only from mutt and fetchmail.

So now I'm past the user name/password/email address config and did the last
couple of steps 

Configure::write('App.setupMode', FALSE);
Configure::write('App.allowPublicAccountCreation', FALSE);

manually as instructed.

But I get dozens of "Notice (8):[function_compact]:" messages with every
click, making the system just about unusable even though they're only
warnings.

After a few random clicks I encountered "Missing Database Table" so it
looks like (as I suspected) the database set up in not done yet,
which brings me back to the SQL error I reported in the first post.

I'll keep ivestigating, but it would be nice to be able to fix this
undefined variable notice in compact().  This is the first instance
of this:

	$result = call_user_func_array(array($this->_loaded[$name], $callback), compact('subject') + $params);

'subject' is the problem.  What needs to be added to make 'subject'
defined properly?

**Comment by nazgul26** [comment]
I will start work on upgrading to CakePHP and that should resolve the PHP 7.2+ issues.
