### ISSUE TITLE
Installed v5.1.5 but lots of things are not working possible json_encode() problem

### ISSUE THREAD

**Issue by guardian46w** [nazgul26/PHPRecipebook#91]
Environment:
CentOS 8.1.1911
Apache 2.4.37
PHP 7.2.11
MariaDB 10.3.17

**List Stores**
`Call to undefined function json_encode()
APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/FormHelper.php line 1923
→
Helper->_confirm(string, string, string, array)
APP/View/Stores/index.ctp line 18
`
Seems that most of the issues are with the "function json_encode()

Anyone have any fixes for this?

**Comment by guardian46w** [comment]
Resolved this issue with --

`yum install php-json`

Still checking thru the app for other issues but so far, so good.

**Comment by nazgul26** [comment]
Good to hear.
