### ISSUE TITLE
Lots of things not working correctly

### ISSUE THREAD

**Issue by eliwap** [nazgul26/PHPRecipebook#92]
First when I download the master zip file, the Plugin folder is missing and the Vendor folder is empty. You can see that while navigating on the main page.

Likewise on the 5.1.5 branch, the Plugin folder is missing.

Recently, I was forced to update my web server to run on php 7.4. With the current working version. I believe it to be version 5.1.1 downloaded some time ago from sourceforge.

I am getting a lot of notices :(

Included is a screen shot of the errors I am getting.

![errors](https://user-images.githubusercontent.com/10329392/78032003-01613a00-736d-11ea-9bb8-350be12e8f06.png)

I would really miss this app if I can't get it to work

**Comment by nazgul26** [comment]
Try the releases from - https://github.com/nazgul26/PHPRecipebook/releases
That will include all the vendor (CakePHP) files.   You will still most likely have to install mcrypt via PECL - i.e. https://lukasmestan.com/install-mcrypt-extension-in-php7-2/

I am going to start working on updating to CakePHP 3.x which will help, but that will take at least a month.

**Comment by eliwap** [comment]
Thanks for responding... I am looking forward to the update :).

Fortuneately Remi provides php-mcrypt for CentOS 7. and php 7.4.

But it did not help. Here is a screenshot of the home page when first visiting the site after updating the files.
![errors_2](https://user-images.githubusercontent.com/10329392/78107079-7c723100-73fd-11ea-8309-b57077b9a714.png)

**Comment by eliwap** [comment]
Any progress?

**Comment by malkavi** [comment]
I'm also interested in the CakePHP update, I'm using PHP 5.4 and have the same "Notice". Any news on this?

**Comment by JustAnotherSysadmin** [comment]
Thank you so much for writing PHPRecipeBook!  My wife and I have been using it for many years now to share 4 generations of family recipes.

I just upgraded to Debian buster and PHP 7.3.  It appears CakePHP has an incompatibility that is being discussed here for different software that also relies on CakePHP:  https://github.com/Sonerezh/sonerezh/issues/372

Hope that helps!

**Comment by eliwap** [comment]
I just compared the diffs with the installation of cake included in phprecipebook. The files pointed to in the discussion you mention are really really different from the files in phprecipebook. Oh well

**Comment by eliwap** [comment]
![phprecipebook_problems](https://user-images.githubusercontent.com/10329392/89010464-4bf0c400-d317-11ea-9ff7-dd6f5b72d816.png)
OK.... well.... sorta... I tried an experiment and things aren't perfect, but... lots better.

If you want to try this... make a backup of your current installation.

First... I went the root folder of the phprecipebook installation and then

cd Vendor
rm -f /bin/*
rm -Rf cakephp
cd composer
rm -Rf *

**** As per https://getcomposer.org/download/

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

php composer.phar install

*** Answer yes

php composer.phar update

**Comment by eliwap** [comment]
Yay!!!!!

Last modification

In the Model folder.... I modified the last 2 functions in User.php from

    public function isAdmin($user) {
        $adminRole = Configure::read('AuthRoles.admin');
        return $user['access_level'] >= $adminRole;
    }

    public function isEditor($user) {
        $editorRole = Configure::read('AuthRoles.editor');
        return $user['access_level'] >= $editorRole;
    }

to

    public function isAdmin($user) {
        $adminRole = Configure::read('AuthRoles.admin');
        if ((isset($user['access_level']) && $user['access_level'] >= $adminRole)) {
          return $user['access_level'] >= $adminRole;
        }
    }

    public function isEditor($user) {
        $editorRole = Configure::read('AuthRoles.editor');
        if ((isset($user['access_level']) && $user['access_level'] >= $editorRole)) {
          return $user['access_level'] >= $editorRole;
        }
    }

**Comment by eliwap** [comment]
Ooops... I did not mean to close the issue.... I don't think this was my place to do so :)

**Comment by DeathStapler** [comment]
What I had to do is turn off debug mode in the `./Config/core.php` file.

It was:
`Configure::write('debug', 2);`

Changed it to:
`Configure::write('debug', 0);`

See it here:
https://github.com/nazgul26/PHPRecipebook/blob/ae8b7bd0af73f5b47dab96d684aa7f6b0f53e065/Config/core.php#L261

**Comment by withanhdammit** [comment]
> What I had to do is turn off debug mode in the `./Config/core.php` file.
> 
> It was:
> `Configure::write('debug', 2);`
> 
> Changed it to:
> `Configure::write('debug', 0);`
> 
> See it here:
> https://github.com/nazgul26/PHPRecipebook/blob/ae8b7bd0af73f5b47dab96d684aa7f6b0f53e065/Config/core.php#L261

+1
This worked for me as well.  I lost my original server, the new one was PHP 7.4, same issue, and disabling debug was the ticket!

**Comment by nazgul26** [comment]
I have checked in your changes.  

I am targeting January 2021 for PHPRecipebook 6.0.  Next release will use CakePHP 3.9 and support current version of Ubuntu/PHP.  No schema changes so the upgrade should be breeze.

Glad to hear the app has been helping you for all this time!
