### ISSUE TITLE
php composer.phar install fails on Debian 10

### ISSUE THREAD

**Issue by afc54** [nazgul26/PHPRecipebook#99]
Trying again to get phprecipebook going.  Just did a git pull from a Debian 10 system completely up to date and

php composer.phar install

fails with this message:
[Composer\Json\JsonValidationException]                                      
  "./composer.json" does not match the expected JSON schema:                   
   - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z  
  0-9](([_.]?|-{0,2})[a-z0-9]+)*$

In red background.  Not sure if this is one of the issues that is being resolved with the upgrade to 6.0 (not yet available apparently) but I thought I'd note it here.  Also, for quite a while now php-mcrypt has not been available.  Is the manual procedure described here:

https://askubuntu.com/questions/1031921/php-mcrypt-package-missing-in-ubuntu-server-18-04-lts

still necessary? or is this another issue that's being resolved in the 6.0 release?  I've tried 2 installations: on a system where I had tried before and on freshly installed system.  On the first phprecipebook at least starts but doesn't really work.  On the latter all I get is a blank page.

**Comment by afc54** [comment]
Got a little further.  The "name" field in composer.json has to be changed to:
    "name": "nazgul26/phprecipebook",
as the new composer requires a vendor name, a forward slash and an all-lowercase package name.
After a php composer.phar update, which gave this warning:

The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

php composer.phar install

succeeded.

**Comment by nazgul26** [comment]
Fixed in v6.0
